use std::fmt::Write as _;

use crate::envelope::remote_transport_error_codes;

pub fn remote_transport_error_code_strings() -> Vec<&'static str> {
    remote_transport_error_codes()
        .iter()
        .map(|code| code.as_str())
        .collect()
}

pub fn generated_stdio_envelope_ts() -> String {
    let mut output = String::new();
    output.push_str("// Generated by `cargo run -p xtask -- export-stdio-transport-contract`.\n");
    output.push_str("// Source of truth: crates/library-boundary-stdio/src/envelope.rs\n\n");
    output.push_str("export const libraryBoundaryStdioRemoteErrorCodes = [\n");
    for code in remote_transport_error_code_strings() {
        let quoted = serde_json::to_string(code).expect("serialize stdio remote error code");
        writeln!(&mut output, "  {quoted},").expect("write generated TypeScript");
    }
    output.push_str("] as const;\n\n");
    output.push_str("export type LibraryBoundaryStdioRemoteErrorCode =\n");
    output.push_str("  (typeof libraryBoundaryStdioRemoteErrorCodes)[number];\n\n");
    output.push_str("const libraryBoundaryStdioRemoteErrorCodeSet = new Set<string>(\n");
    output.push_str("  libraryBoundaryStdioRemoteErrorCodes\n");
    output.push_str(");\n\n");
    output.push_str("export function isLibraryBoundaryStdioRemoteErrorCode(\n");
    output.push_str("  value: string\n");
    output.push_str("): value is LibraryBoundaryStdioRemoteErrorCode {\n");
    output.push_str("  return libraryBoundaryStdioRemoteErrorCodeSet.has(value);\n");
    output.push_str("}\n");
    output
}

#[cfg(test)]
mod tests {
    use super::{generated_stdio_envelope_ts, remote_transport_error_code_strings};

    #[test]
    fn remote_error_code_strings_are_exact_stdout_envelope_codes() {
        assert_eq!(
            remote_transport_error_code_strings(),
            vec![
                "invalidFrame",
                "invalidEnvelope",
                "invalidRequestId",
                "invalidCommandRequest",
                "serverPanic",
                "stdinReadFailure"
            ]
        );
    }

    #[test]
    fn generated_stdio_envelope_typescript_is_deterministic() {
        assert_eq!(generated_stdio_envelope_ts(), generated_stdio_envelope_ts());
    }

    #[test]
    fn generated_stdio_envelope_typescript_excludes_non_stdout_failures() {
        let generated = generated_stdio_envelope_ts();

        assert!(generated.contains("\"invalidFrame\""));
        assert!(generated.contains("\"stdinReadFailure\""));
        assert!(!generated.contains("stdoutWriteFailure"));
        assert!(!generated.contains("serviceOpenFailure"));
    }
}
