use std::fmt::Write as _;

use crate::envelope::{ready_envelope_type, ready_server_string, remote_transport_error_codes};

pub fn remote_transport_error_code_strings() -> Vec<&'static str> {
    remote_transport_error_codes()
        .iter()
        .map(|code| code.as_str())
        .collect()
}

pub fn ready_envelope_type_string() -> &'static str {
    ready_envelope_type()
}

pub fn ready_server_string_contract() -> &'static str {
    ready_server_string()
}

pub fn generated_stdio_envelope_ts() -> String {
    let mut output = String::new();
    output.push_str("// Generated by `cargo run -p xtask -- export-stdio-transport-contract`.\n");
    output.push_str("// Source of truth: crates/library-boundary-stdio/src/envelope.rs\n\n");
    let ready_type =
        serde_json::to_string(ready_envelope_type_string()).expect("serialize ready type");
    let ready_server =
        serde_json::to_string(ready_server_string_contract()).expect("serialize ready server");
    writeln!(
        &mut output,
        "export const libraryBoundaryStdioReadyEnvelopeType = {ready_type} as const;"
    )
    .expect("write generated TypeScript");
    writeln!(
        &mut output,
        "export const libraryBoundaryStdioReadyServer = {ready_server} as const;\n"
    )
    .expect("write generated TypeScript");
    output.push_str("export type LibraryBoundaryStdioReadyEnvelope = {\n");
    output.push_str("  readonly type: typeof libraryBoundaryStdioReadyEnvelopeType;\n");
    output.push_str("  readonly server: typeof libraryBoundaryStdioReadyServer;\n");
    output.push_str("};\n\n");
    output.push_str("export function isLibraryBoundaryStdioReadyEnvelope(\n");
    output.push_str("  value: unknown\n");
    output.push_str("): value is LibraryBoundaryStdioReadyEnvelope {\n");
    output.push_str("  if (!isRecord(value)) {\n");
    output.push_str("    return false;\n");
    output.push_str("  }\n\n");
    output.push_str("  return (\n");
    output.push_str("    Object.keys(value).length === 2 &&\n");
    output.push_str("    value.type === libraryBoundaryStdioReadyEnvelopeType &&\n");
    output.push_str("    value.server === libraryBoundaryStdioReadyServer\n");
    output.push_str("  );\n");
    output.push_str("}\n\n");
    output.push_str("export const libraryBoundaryStdioRemoteErrorCodes = [\n");
    for code in remote_transport_error_code_strings() {
        let quoted = serde_json::to_string(code).expect("serialize stdio remote error code");
        writeln!(&mut output, "  {quoted},").expect("write generated TypeScript");
    }
    output.push_str("] as const;\n\n");
    output.push_str("export type LibraryBoundaryStdioRemoteErrorCode =\n");
    output.push_str("  (typeof libraryBoundaryStdioRemoteErrorCodes)[number];\n\n");
    output.push_str("const libraryBoundaryStdioRemoteErrorCodeSet = new Set<string>(\n");
    output.push_str("  libraryBoundaryStdioRemoteErrorCodes\n");
    output.push_str(");\n\n");
    output.push_str("export function isLibraryBoundaryStdioRemoteErrorCode(\n");
    output.push_str("  value: string\n");
    output.push_str("): value is LibraryBoundaryStdioRemoteErrorCode {\n");
    output.push_str("  return libraryBoundaryStdioRemoteErrorCodeSet.has(value);\n");
    output.push_str("}\n");
    output.push_str("\nfunction isRecord(value: unknown): value is Record<string, unknown> {\n");
    output.push_str(
        "  return typeof value === \"object\" && value !== null && !Array.isArray(value);\n",
    );
    output.push_str("}\n");
    output
}

#[cfg(test)]
mod tests {
    use super::{
        generated_stdio_envelope_ts, ready_envelope_type_string, ready_server_string_contract,
        remote_transport_error_code_strings,
    };

    #[test]
    fn ready_envelope_shape_is_exact_stdout_contract() {
        assert_eq!(ready_envelope_type_string(), "ready");
        assert_eq!(ready_server_string_contract(), "libraryBoundaryStdio");
    }

    #[test]
    fn remote_error_code_strings_are_exact_stdout_envelope_codes() {
        assert_eq!(
            remote_transport_error_code_strings(),
            vec![
                "invalidFrame",
                "invalidEnvelope",
                "invalidRequestId",
                "invalidCommandRequest",
                "serverPanic",
                "stdinReadFailure"
            ]
        );
    }

    #[test]
    fn generated_stdio_envelope_typescript_is_deterministic() {
        assert_eq!(generated_stdio_envelope_ts(), generated_stdio_envelope_ts());
    }

    #[test]
    fn generated_stdio_envelope_typescript_excludes_non_stdout_failures() {
        let generated = generated_stdio_envelope_ts();

        assert!(generated.contains("libraryBoundaryStdioReadyEnvelopeType"));
        assert!(generated.contains("\"ready\" as const"));
        assert!(generated.contains("\"libraryBoundaryStdio\" as const"));
        assert!(generated.contains("\"invalidFrame\""));
        assert!(generated.contains("\"stdinReadFailure\""));
        assert!(!generated.contains("stdoutWriteFailure"));
        assert!(!generated.contains("serviceOpenFailure"));
    }
}
