// @generated by cargo run -p xtask -- export-boundary-contract
// Source of truth: crates/library-boundary-protocol
// Do not edit by hand.

export type CommandRequest = { "type": "libraryBoundaryEvents", "payload": LibraryBoundaryEventStreamCommand } | { "type": "libraryRoots", "payload": LibraryRootCommand } | { "type": "playlistWrite", "payload": PlaylistWriteCommand } | { "type": "snapshotRead", "payload": SnapshotReadCommand };

export type LibraryBoundaryEventStreamCommand = { "type": "readPending", "payload": ReadLibraryBoundaryEventsRequest };

export type ReadLibraryBoundaryEventsRequest = { maxEvents: number, };

export type LibraryRootCommand = { "type": "registerLocalRoot", "payload": RegisterLocalRootRequest } | { "type": "runRootScan", "payload": RunRootScanRequest };

export type RegisterLocalRootRequest = { absolutePath: string, };

export type RunRootScanRequest = { rootId: string, };

export type PlaylistWriteCommand = { "type": "createPlaylist", "payload": CreatePlaylistRequest } | { "type": "renamePlaylist", "payload": RenamePlaylistRequest } | { "type": "deletePlaylist", "payload": DeletePlaylistRequest } | { "type": "appendLibraryAssetToPlaylist", "payload": AppendLibraryAssetToPlaylistRequest } | { "type": "removeLibraryAssetFromPlaylist", "payload": RemoveLibraryAssetFromPlaylistRequest } | { "type": "movePlaylistEntry", "payload": MovePlaylistEntryRequest };

export type CreatePlaylistRequest = { displayName: string, };

export type RenamePlaylistRequest = { playlistId: string, displayName: string, };

export type DeletePlaylistRequest = { playlistId: string, };

export type AppendLibraryAssetToPlaylistRequest = { playlistId: string, libraryAssetId: string, };

export type RemoveLibraryAssetFromPlaylistRequest = { playlistId: string, libraryAssetId: string, };

export type MovePlaylistEntryRequest = { playlistId: string, playlistEntryId: string, newPosition: number, };

export type SnapshotReadCommand = { "type": "readNavigationRows", "payload": ReadNavigationRowsRequest } | { "type": "loadNavigationRow", "payload": LoadNavigationRowRequest } | { "type": "loadNavigationRowByStableKey", "payload": LoadNavigationRowByStableKeyRequest } | { "type": "readLiteralHierarchyChildren", "payload": ReadLiteralHierarchyChildrenRequest } | { "type": "readNavigationNodeLibraryBrowserWindow", "payload": ReadNavigationNodeLibraryBrowserWindowRequest } | { "type": "searchNavigationNodeLibraryBrowserWindow", "payload": SearchNavigationNodeLibraryBrowserWindowRequest } | { "type": "readLibraryAssetWaveformOverview", "payload": ReadLibraryAssetWaveformOverviewRequest } | { "type": "readLibraryAssetPreparationDetail", "payload": ReadLibraryAssetPreparationDetailRequest };

export type ReadNavigationRowsRequest = { parentNavigationRowId: string | null, };

export type LoadNavigationRowRequest = { navigationRowId: string, };

export type LoadNavigationRowByStableKeyRequest = { stableKey: string, };

export type ReadLiteralHierarchyChildrenRequest = { entryPoint: LiteralHierarchyEntryPoint, parentSourceDirectoryId: string | null, offset: number, limit: number, };

export type ReadNavigationNodeLibraryBrowserWindowRequest = { navigationRowId: string, offset: number, limit: number, };

export type SearchNavigationNodeLibraryBrowserWindowRequest = { navigationRowId: string, query: string, offset: number, limit: number, };

export type ReadLibraryAssetWaveformOverviewRequest = { libraryAssetId: string, };

export type ReadLibraryAssetPreparationDetailRequest = { libraryAssetId: string, };

export type CommandReply = { "type": "libraryBoundaryEvents", "payload": LibraryBoundaryEventStreamReply } | { "type": "libraryRoots", "payload": LibraryRootReply } | { "type": "playlistWrite", "payload": PlaylistWriteReply } | { "type": "snapshotRead", "payload": SnapshotReadReply };

export type LibraryBoundaryEventStreamReply = { "type": "readPending", "payload": ReadLibraryBoundaryEventsReply };

export type ReadLibraryBoundaryEventsReply = { events: Array<LibraryBoundaryEvent>, };

export type LibraryRootReply = { "type": "registerLocalRoot", "payload": RegisterLocalRootReply } | { "type": "runRootScan", "payload": RunRootScanReply };

export type RegisterLocalRootReply = { rootId: string, canonicalPath: string, };

export type RunRootScanReply = { rootId: string, scanRunId: string, discoveredFileCount: number, queuedSourceWorkItems: number, };

export type PlaylistWriteReply = { "type": "createPlaylist", "payload": CreatePlaylistReply } | { "type": "renamePlaylist", "payload": RenamePlaylistReply } | { "type": "deletePlaylist", "payload": DeletePlaylistReply } | { "type": "appendLibraryAssetToPlaylist", "payload": AppendLibraryAssetToPlaylistReply } | { "type": "removeLibraryAssetFromPlaylist", "payload": RemoveLibraryAssetFromPlaylistReply } | { "type": "movePlaylistEntry", "payload": MovePlaylistEntryReply };

export type CreatePlaylistReply = { playlistId: string, };

export type RenamePlaylistReply = { renamed: boolean, };

export type DeletePlaylistReply = { deleted: boolean, };

export type AppendLibraryAssetToPlaylistReply = { playlistEntryId: string, };

export type RemoveLibraryAssetFromPlaylistReply = { removed: boolean, };

export type MovePlaylistEntryReply = { moved: boolean, };

export type SnapshotReadReply = { "type": "navigationRows", "payload": ReadNavigationRowsReply } | { "type": "navigationRow", "payload": LoadNavigationRowReply } | { "type": "navigationRowByStableKey", "payload": LoadNavigationRowByStableKeyReply } | { "type": "literalHierarchyChildren", "payload": ReadLiteralHierarchyChildrenReply } | { "type": "navigationNodeLibraryBrowserWindow", "payload": ReadNavigationNodeLibraryBrowserWindowReply } | { "type": "navigationNodeLibraryBrowserSearch", "payload": SearchNavigationNodeLibraryBrowserWindowReply } | { "type": "libraryAssetWaveformOverview", "payload": ReadLibraryAssetWaveformOverviewReply } | { "type": "libraryAssetPreparationDetail", "payload": ReadLibraryAssetPreparationDetailReply };

export type ReadNavigationRowsReply = { rows: Array<NavigationRow>, };

export type LoadNavigationRowReply = { row: NavigationRow | null, };

export type LoadNavigationRowByStableKeyReply = { row: NavigationRow | null, };

export type ReadLiteralHierarchyChildrenReply = { window: LiteralHierarchyWindow | null, };

export type ReadNavigationNodeLibraryBrowserWindowReply = { window: LibraryBrowserWindow | null, };

export type SearchNavigationNodeLibraryBrowserWindowReply = { window: LibraryBrowserWindow | null, };

export type ReadLibraryAssetWaveformOverviewReply = { overview: LibraryAssetWaveformOverview | null, };

export type ReadLibraryAssetPreparationDetailReply = { detail: LibraryAssetPreparationDetail | null, };

export type NavigationRow = { navigationRowId: string, stableKey: string, parentNavigationRowId: string | null, family: NavigationRowFamily | null, rowKind: NavigationRowKind, displayName: string, siblingPosition: number, selectable: boolean, selectorKind: NavigationRowSelectorKind | null, selectorPayload: string | null, updatedAtMs: number, rowVersion: string, };

export type NavigationRowFamily = "views" | "collections" | "preparation" | "sources";

export type NavigationRowKind = "view" | "collectionGroup" | "playlist" | "prepPolicyGroup" | "prepPolicyScope" | "source" | "locationGroup" | "location";

export type NavigationRowSelectorKind = "allMedia" | "allAudio" | "allVideos" | "recentlyAdded" | "needsPreparation" | "playlistGroup" | "source" | "sourceLocation" | "playlist" | "prepPolicyScope";

export type LiteralHierarchyEntryPoint = { "type": "source", "payload": { sourceId: string, } } | { "type": "sourceLocation", "payload": { sourceLocationId: string, } };

export type LiteralHierarchyWindow = { entryPoint: LiteralHierarchyEntryPoint, parentSourceDirectoryId: string | null, offset: number, limit: number, totalRows: number, rows: Array<LiteralHierarchyNode>, };

export type LiteralHierarchyNode = { nodeKind: LiteralHierarchyNodeKind, sourceId: string, sourceDirectoryId: string | null, sourceFileId: string | null, parentSourceDirectoryId: string | null, relativePath: string, displayName: string, presenceState: LiteralHierarchyPresenceState, sizeBytes: number | null, modifiedAtNs: number | null, updatedAtMs: number, };

export type LiteralHierarchyNodeKind = "directory" | "file";

export type LiteralHierarchyPresenceState = "present" | "missing" | "removed";

export type LibraryBrowserWindow = { offset: number, limit: number, totalRows: number, rows: Array<LibraryAssetBrowserRow>, };

export type LibraryAssetBrowserRow = { libraryAssetId: string, rowVersion: string, primarySourceFileId: string | null, scopedSourceFileId: string | null, sourceId: string | null, relativePath: string | null, fileName: string | null, availabilityState: LibraryAssetAvailabilityState, title: string | null, artist: string | null, album: string | null, durationMs: number | null, musicalKey: string | null, tempoBpm: number | null, 
/**
 * Browse-facing summaries derived by projection rebuild logic from
 * capability/artifact state; they are not canonical authority.
 */
waveformQualityCurrent: number | null, waveformQualityTarget: number | null, stemsStateSummary: LibraryAssetStemsStateSummary | null, prepReadinessSummary: LibraryAssetPrepReadinessSummary, updatedAtMs: number, };

export type LibraryAssetAvailabilityState = "available" | "unavailable" | "degraded";

export type LibraryAssetStemsStateSummary = "missing" | "queued" | "leased" | "ready" | "stale" | "blocked" | "failed";

export type LibraryAssetPrepReadinessSummary = "notRequired" | "ready" | "preparing" | "underprepared" | "blocked" | "failed";

export type LibraryAssetPreparationDetail = { libraryAssetId: string, aggregateReadinessSummary: LibraryAssetPrepReadinessSummary, groups: Array<LibraryAssetPreparationDetailGroup>, };

export type LibraryAssetPreparationDetailGroup = { groupKey: LibraryAssetPreparationDetailGroupKey, rows: Array<LibraryAssetPreparationDetailRow>, };

export type LibraryAssetPreparationDetailGroupKey = "requiredFacts" | "requiredStructures" | "requiredArtifacts" | "onDemandCapabilities";

export type LibraryAssetPreparationDetailRow = { capabilityKey: LibraryAssetPreparationCapabilityKey, label: string, requirementClass: LibraryAssetPreparationRequirementClass, outcomeKind: LibraryAssetPreparationOutcomeKind, workState: LibraryAssetPreparationWorkState, outcomeState: LibraryAssetPreparationOutcomeState, satisfactionState: LibraryAssetPreparationSatisfactionState, displayValueSummary: string | null, targetSummary: string | null, explanationSummary: string | null, artifactCoverageState: LibraryAssetPreparationArtifactCoverageState | null, progress: LibraryAssetPreparationProgress | null, };

export type LibraryAssetPreparationCapabilityKey = "bpm" | "musicalKey" | "beatgrid" | "waveform" | "stems";

export type LibraryAssetPreparationRequirementClass = "required" | "onDemand";

export type LibraryAssetPreparationOutcomeKind = "fact" | "structure" | "artifact";

export type LibraryAssetPreparationWorkState = "none" | "notRequested" | "queued" | "active" | "blocked" | "failed";

export type LibraryAssetPreparationOutcomeState = "missing" | "provisional" | "ready" | "stale";

export type LibraryAssetPreparationSatisfactionState = "satisfied" | "unsatisfied";

export type LibraryAssetPreparationArtifactCoverageState = "none" | "previewReady" | "overviewReady" | "refinementAvailable" | "stale";

export type LibraryAssetPreparationProgress = { "type": "indeterminate", activeStage: string | null, } | { "type": "boundedStage", activeStage: string | null, completedUnits: number, totalUnits: number, fraction: number, };

export type LibraryAssetWaveformOverview = { sourceProfileKey: string, sourceQualityCurrent: number | null, capabilityState: LibraryAssetWaveformOverviewCapabilityState, amplitudeScale: LibraryAssetWaveformOverviewAmplitudeScale, bucketCount: number, durationMs: number | null, sourceSampleCount: number | null, samplesPerBucket: number | null, buckets: Array<LibraryAssetWaveformOverviewBucket>, acceptedArtifactId: string, basisFingerprint: string, capabilityUpdatedAtMs: number, artifactCreatedAtMs: number, };

export type LibraryAssetWaveformOverviewBucket = { minAmplitudeI16: number, maxAmplitudeI16: number, };

export type LibraryAssetWaveformOverviewCapabilityState = "ready" | "stale";

export type LibraryAssetWaveformOverviewAmplitudeScale = "signedI16";

export type CommandOutcome = { "type": "success", "payload": CommandSuccessEnvelope } | { "type": "error", "payload": CommandErrorEnvelope };

export type CommandSuccessEnvelope = { reply: CommandReply, };

export type CommandErrorEnvelope = { error: ProtocolError, };

export type ProtocolError = { "type": "invalidRequest", "payload": { detail: string, } } | { "type": "durableStoreFailure", "payload": { detail: string, } } | { "type": "hostFailure", "payload": { detail: string, } };

export type LibraryBoundaryEvent = { "type": "maintainedSnapshotInvalidated", "payload": MaintainedSnapshotInvalidation };

export type MaintainedSnapshotInvalidation = { scope: MaintainedSnapshotScope, revision: MaintainedSnapshotRevision | null, };

export type MaintainedSnapshotScopeRevision = { scope: MaintainedSnapshotScope, revision: MaintainedSnapshotRevision, };

export type MaintainedSnapshotScope = "navigationRows" | "libraryBrowser";

export type MaintainedSnapshotRevision = string;

export type LibraryBoundaryContract = { commandRequest: CommandRequest, commandOutcome: CommandOutcome, protocolError: ProtocolError, libraryBoundaryEvent: LibraryBoundaryEvent, };

