// @generated by cargo run -p xtask -- export-boundary-contract
// Source of truth: crates/library-boundary-protocol
// Do not edit by hand.

export type CommandRequest = { "type": "libraryBoundaryEvents", "payload": LibraryBoundaryEventStreamCommand } | { "type": "libraryRoots", "payload": LibraryRootCommand } | { "type": "playlistWrite", "payload": PlaylistWriteCommand } | { "type": "sourceFileHash", "payload": SourceFileHashCommand } | { "type": "sourceMaintenance", "payload": SourceMaintenanceCommand } | { "type": "snapshotRead", "payload": SnapshotReadCommand };

export type LibraryBoundaryEventStreamCommand = { "type": "readAfter", "payload": ReadLibraryBoundaryEventsAfterRequest };

export type ReadLibraryBoundaryEventsAfterRequest = { 
/**
 * The last event sequence the caller has already observed.
 * `None` means start from the beginning.
 */
lastSeenEventSequence: number | null, maxEvents: number, };

export type LibraryRootCommand = { "type": "registerLocalRoot", "payload": RegisterLocalRootRequest } | { "type": "startRootScan", "payload": StartRootScanRequest } | { "type": "readLocalRoots", "payload": ReadLocalRootsRequest } | { "type": "unregisterLocalRoot", "payload": UnregisterLocalRootRequest } | { "type": "cancelRootScan", "payload": CancelRootScanRequest };

export type RegisterLocalRootRequest = { absolutePath: string, };

export type StartRootScanRequest = { rootId: string, };

export type CancelRootScanRequest = { scanRunId: string, };

export type CancelRootScanStatus = "accepted" | "notFound" | "alreadyTerminal" | "notCancelable";

export type ReadLocalRootsRequest = null;

export type UnregisterLocalRootRequest = { rootId: string, };

export type LocalRootAvailability = "available" | "unavailable";

export type LocalRoot = { rootId: string, canonicalPath: string, availability: LocalRootAvailability, };

export type PlaylistWriteCommand = { "type": "createPlaylist", "payload": CreatePlaylistRequest } | { "type": "renamePlaylist", "payload": RenamePlaylistRequest } | { "type": "deletePlaylist", "payload": DeletePlaylistRequest } | { "type": "appendLibraryAssetToPlaylist", "payload": AppendLibraryAssetToPlaylistRequest } | { "type": "removeLibraryAssetFromPlaylist", "payload": RemoveLibraryAssetFromPlaylistRequest } | { "type": "movePlaylistEntry", "payload": MovePlaylistEntryRequest };

export type CreatePlaylistRequest = { displayName: string, };

export type RenamePlaylistRequest = { playlistId: string, displayName: string, };

export type DeletePlaylistRequest = { playlistId: string, };

export type AppendLibraryAssetToPlaylistRequest = { playlistId: string, libraryAssetId: string, };

export type RemoveLibraryAssetFromPlaylistRequest = { playlistId: string, libraryAssetId: string, };

export type MovePlaylistEntryRequest = { playlistId: string, playlistEntryId: string, newPosition: number, };

export type SourceFileHashCommand = { "type": "hashSourceFilesBlake3", "payload": HashSourceFilesBlake3Request };

export type HashSourceFilesBlake3Request = { sourceId: string, limit?: number, };

export type SourceMaintenanceCommand = { "type": "runSourceMaintenance", "payload": RunSourceMaintenanceRequest };

export type RunSourceMaintenanceRequest = { sourceId: string, hashLimit?: number, attachmentLimit?: number, probeLimit?: number, promotionLimit?: number, identityCandidateLimit?: number, };

export type SnapshotReadCommand = { "type": "readNavigationRows", "payload": ReadNavigationRowsRequest } | { "type": "loadNavigationRow", "payload": LoadNavigationRowRequest } | { "type": "loadNavigationRowByStableKey", "payload": LoadNavigationRowByStableKeyRequest } | { "type": "readLibraryTreeChildren", "payload": ReadLibraryTreeChildrenRequest } | { "type": "readSourceLifecycle", "payload": ReadSourceLifecycleRequest } | { "type": "readSourceMaintenance", "payload": ReadSourceMaintenanceRequest } | { "type": "readSourceFileAttachment", "payload": ReadSourceFileAttachmentRequest } | { "type": "readAttachmentSourceFiles", "payload": ReadAttachmentSourceFilesRequest } | { "type": "readSourceAttachmentSummary", "payload": ReadSourceAttachmentSummaryRequest } | { "type": "readNavigationNodeLibraryBrowserWindow", "payload": ReadNavigationNodeLibraryBrowserWindowRequest } | { "type": "searchNavigationNodeLibraryBrowserWindow", "payload": SearchNavigationNodeLibraryBrowserWindowRequest } | { "type": "contentsRead", "payload": ContentsReadRequest } | { "type": "readLibraryAssetWaveformOverview", "payload": ReadLibraryAssetWaveformOverviewRequest } | { "type": "readLibraryAssetPreparationDetail", "payload": ReadLibraryAssetPreparationDetailRequest };

export type ReadNavigationRowsRequest = { parentNavigationRowId: string | null, };

export type LoadNavigationRowRequest = { navigationRowId: string, };

export type LoadNavigationRowByStableKeyRequest = { stableKey: string, };

export type ReadLibraryTreeChildrenRequest = { entryPoint: LibraryTreeEntryPoint, parentSourceDirectoryId: string | null, offset: number, limit: number, };

export type ChildRowState = "unknown" | "hasChildRows" | "noChildRows";

export type ReadSourceLifecycleRequest = { sourceId: string, };

export type ReadSourceMaintenanceRequest = { sourceId: string, };

export type SourceClass = "internal" | "externalMounted" | "removableMounted";

export type SourceMountStatus = "unknown" | "mounted" | "unmounted" | "ejectRequested" | "ejectPending";

export type SourceAccessState = "accessible" | "missing" | "blocked" | "unknown";

export type SourceLifecycleIssueKind = "missing" | "notDirectory" | "permissionDenied" | "privacyPermissionRequired" | "unavailableMount" | "resourceBusy" | "staleNetworkHandle" | "symlinkLoop" | "symlinkEscapeBlocked" | "unsupportedPath" | "invalidPath" | "ioInterrupted" | "timedOut" | "unknownIo";

export type SourceScanPhase = "idle" | "scanning" | "complete" | "partial" | "blocked" | "failed";

export type ReadSourceFileAttachmentRequest = { sourceFileId: string, };

export type ReadAttachmentSourceFilesRequest = { attachmentId: string, limit?: number, };

export type ReadSourceAttachmentSummaryRequest = { sourceId: string, };

export type ReadNavigationNodeLibraryBrowserWindowRequest = { navigationRowId: string, offset: number, limit: number, };

export type SearchNavigationNodeLibraryBrowserWindowRequest = { navigationRowId: string, query: string, offset: number, limit: number, };

export type ContentsReadRequest = { scope: ContentsScope, policy: ContentsReadPolicy, recursion: ContentsRecursion, limit?: number, cursor?: string, };

export type ContentsScope = { "type": "source", "payload": { sourceId: string, } } | { "type": "sourceLocation", "payload": { sourceLocationId: string, } } | { "type": "directory", "payload": { sourceId: string, sourceDirectoryId: string, } };

export type ContentsReadPolicy = { mediaClasses: Array<ContentsMediaClass>, rowProfile: ContentsRowProfile, };

export type ContentsRowProfile = { "kind": "sourceFile" } | { "kind": "primaryMedia" };

export type ContentsRecursion = "immediate" | "recursive";

export type ReadLibraryAssetWaveformOverviewRequest = { libraryAssetId: string, };

export type ReadLibraryAssetPreparationDetailRequest = { libraryAssetId: string, };

export type CommandReply = { "type": "libraryBoundaryEvents", "payload": LibraryBoundaryEventStreamReply } | { "type": "libraryRoots", "payload": LibraryRootReply } | { "type": "playlistWrite", "payload": PlaylistWriteReply } | { "type": "sourceFileHash", "payload": SourceFileHashReply } | { "type": "sourceMaintenance", "payload": SourceMaintenanceReply } | { "type": "snapshotRead", "payload": SnapshotReadReply };

export type LibraryBoundaryEventStreamReply = { "type": "readAfter", "payload": ReadLibraryBoundaryEventsAfterReply };

export type ReadLibraryBoundaryEventsAfterReply = { events: Array<LibraryBoundaryEvent>, 
/**
 * The cursor the consumer should pass as `lastSeenEventSequence` in
 * the next read-after call.  It is the event sequence of the last
 * event delivered in this reply, or the previously supplied
 * `lastSeenEventSequence` when no new events were returned, or
 * `None` when no events have been published yet.
 */
latestEventSequence: number | null, 
/**
 * The earliest sequence still retained in the event ring buffer.
 * If the caller asks for events after a sequence lower than this,
 * some events have been compacted away.
 */
earliestRetainedSequence: number | null, 
/**
 * True when the caller's `lastSeenEventSequence` is older than the
 * earliest retained event, meaning events were compacted away.
 */
gapDetected: boolean, };

export type LibraryRootReply = { "type": "registerLocalRoot", "payload": RegisterLocalRootReply } | { "type": "startRootScan", "payload": StartRootScanReply } | { "type": "readLocalRoots", "payload": ReadLocalRootsReply } | { "type": "unregisterLocalRoot", "payload": UnregisterLocalRootReply } | { "type": "cancelRootScan", "payload": CancelRootScanReply };

export type RegisterLocalRootReply = { rootId: string, canonicalPath: string, };

export type StartRootScanReply = { scanRunId: string, };

export type CancelRootScanReply = { status: CancelRootScanStatus, };

export type ReadLocalRootsReply = { roots: Array<LocalRoot>, };

export type UnregisterLocalRootReply = { unregistered: boolean, };

export type PlaylistWriteReply = { "type": "createPlaylist", "payload": CreatePlaylistReply } | { "type": "renamePlaylist", "payload": RenamePlaylistReply } | { "type": "deletePlaylist", "payload": DeletePlaylistReply } | { "type": "appendLibraryAssetToPlaylist", "payload": AppendLibraryAssetToPlaylistReply } | { "type": "removeLibraryAssetFromPlaylist", "payload": RemoveLibraryAssetFromPlaylistReply } | { "type": "movePlaylistEntry", "payload": MovePlaylistEntryReply };

export type CreatePlaylistReply = { playlistId: string, };

export type RenamePlaylistReply = { renamed: boolean, };

export type DeletePlaylistReply = { deleted: boolean, };

export type AppendLibraryAssetToPlaylistReply = { playlistEntryId: string, };

export type RemoveLibraryAssetFromPlaylistReply = { removed: boolean, };

export type MovePlaylistEntryReply = { moved: boolean, };

export type SourceFileHashReply = { "type": "hashSourceFilesBlake3", "payload": HashSourceFilesBlake3Reply };

export type HashSourceFilesBlake3Reply = { effectiveLimit: number, outcomes: Array<HashSourceFilesBlake3Outcome>, hashedCount: number, skippedCount: number, failedCount: number, remainingCandidates: number, sourceFailure?: HashSourceFilesBlake3SourceFailure, };

export type SourceMaintenanceReply = { "type": "runSourceMaintenance", "payload": RunSourceMaintenanceReply };

export type RunSourceMaintenanceReply = { sourceId: string, status: SourceMaintenanceRunStatus, effectiveLimits: SourceMaintenanceEffectiveLimits, hash: SourceMaintenanceHashSummary, attachmentMaterialization: SourceMaintenanceAttachmentMaterializationSummary, probe: SourceMaintenanceProbeSummary, primaryMediaPromotion: SourceMaintenancePrimaryMediaPromotionSummary, trackIdentityCandidates: SourceMaintenanceTrackIdentityCandidateSummary, remainingHashCandidates: number, remainingProbeCandidates: number, remainingPrimaryMediaPromotionCandidates: number, remainingTrackIdentityCandidateProductionCandidates: number, attachmentLinks?: SourceMaintenanceAttachmentLinkSummary, sourceFailure?: SourceMaintenanceSourceFailure, };

export type SnapshotReadReply = { "type": "navigationRows", "payload": ReadNavigationRowsReply } | { "type": "navigationRow", "payload": LoadNavigationRowReply } | { "type": "navigationRowByStableKey", "payload": LoadNavigationRowByStableKeyReply } | { "type": "libraryTreeChildren", "payload": ReadLibraryTreeChildrenReply } | { "type": "sourceLifecycle", "payload": ReadSourceLifecycleReply } | { "type": "sourceMaintenance", "payload": ReadSourceMaintenanceReply } | { "type": "sourceFileAttachment", "payload": ReadSourceFileAttachmentReply } | { "type": "attachmentSourceFiles", "payload": ReadAttachmentSourceFilesReply } | { "type": "sourceAttachmentSummary", "payload": ReadSourceAttachmentSummaryReply } | { "type": "navigationNodeLibraryBrowserWindow", "payload": ReadNavigationNodeLibraryBrowserWindowReply } | { "type": "navigationNodeLibraryBrowserSearch", "payload": SearchNavigationNodeLibraryBrowserWindowReply } | { "type": "contents", "payload": ContentsReadReply } | { "type": "libraryAssetWaveformOverview", "payload": ReadLibraryAssetWaveformOverviewReply } | { "type": "libraryAssetPreparationDetail", "payload": ReadLibraryAssetPreparationDetailReply };

export type ReadNavigationRowsReply = { rows: Array<NavigationRow>, };

export type LoadNavigationRowReply = { row: NavigationRow | null, };

export type LoadNavigationRowByStableKeyReply = { row: NavigationRow | null, };

export type ReadLibraryTreeChildrenReply = { window: LibraryTreeWindow | null, };

export type ReadSourceLifecycleReply = { lifecycle: SourceLifecycle | null, };

export type ReadSourceMaintenanceReply = { sourceId: string, status: SourceMaintenanceSnapshotStatus, remainingHashCandidates: number, remainingProbeCandidates: number, remainingPrimaryMediaPromotionCandidates: number, remainingTrackIdentityCandidateProductionCandidates: number, attachmentLinks?: SourceMaintenanceAttachmentLinkSummary, sourceFailure?: SourceMaintenanceSourceFailure, lastRun?: SourceMaintenanceLastRunSummary, };

export type ReadSourceFileAttachmentReply = { status: AttachmentIdentityReadStatus, attachmentLink?: SourceFileAttachmentLink, };

export type ReadAttachmentSourceFilesReply = { status: AttachmentIdentityReadStatus, attachment?: AttachmentIdentity, sourceFileLinks: Array<SourceFileAttachmentLink>, effectiveLimit: number, remainingSourceFileLinks: number, };

export type ReadSourceAttachmentSummaryReply = { status: AttachmentIdentityReadStatus, summary?: SourceAttachmentSummary, };

export type ReadNavigationNodeLibraryBrowserWindowReply = { window: LibraryBrowserWindow | null, };

export type SearchNavigationNodeLibraryBrowserWindowReply = { window: LibraryBrowserWindow | null, };

export type ContentsReadReply = { result: ContentsResult, };

export type ReadLibraryAssetWaveformOverviewReply = { overview: LibraryAssetWaveformOverview | null, };

export type ReadLibraryAssetPreparationDetailReply = { detail: LibraryAssetPreparationDetail | null, };

export type NavigationRow = { navigationRowId: string, stableKey: string, parentNavigationRowId: string | null, family: NavigationRowFamily | null, rowKind: NavigationRowKind, displayName: string, siblingPosition: number, selectable: boolean, selectorKind: NavigationRowSelectorKind | null, selectorPayload: string | null, updatedAtMs: number, rowVersion: string, };

export type NavigationRowFamily = "views" | "collections" | "preparation" | "sources";

export type NavigationRowKind = "view" | "collectionGroup" | "playlist" | "prepPolicyGroup" | "prepPolicyScope" | "source" | "locationGroup" | "location";

export type NavigationRowSelectorKind = "allMedia" | "allAudio" | "allVideos" | "recentlyAdded" | "needsPreparation" | "playlistGroup" | "source" | "sourceLocation" | "playlist" | "prepPolicyScope";

export type LibraryTreeEntryPoint = { "type": "source", "payload": { sourceId: string, } } | { "type": "sourceLocation", "payload": { sourceLocationId: string, } };

export type LibraryTreeWindow = { entryPoint: LibraryTreeEntryPoint, parentSourceDirectoryId: string | null, offset: number, limit: number, totalRows: number, rows: Array<LibraryTreeNode>, coverage: LibraryTreeCoverage, };

export type LibraryTreeCoverage = { state: LibraryTreeCoverageState, recursiveScopeComplete: boolean, emptyResultAuthoritative: boolean, detail: string | null, };

export type LibraryTreeCoverageState = "complete" | "pending" | "scanning" | "blocked" | "failed" | "sourceUnavailable" | "locationMissing";

export type LibraryTreeNode = { nodeKind: LibraryTreeNodeKind, sourceId: string, sourceDirectoryId: string | null, sourceFileId: string | null, parentSourceDirectoryId: string | null, relativePath: string, displayName: string, mediaClass?: LibraryTreeFileMediaClass, presenceState: LibraryTreePresenceState, sizeBytes: number | null, modifiedAtNs: number | null, updatedAtMs: number, hasChildDirectories?: boolean, directoryPrimaryMediaState?: DirectoryPrimaryMediaState, directoryImageMediaState?: DirectoryImageMediaState, directoryScanState?: DirectoryScanState, childRowState?: ChildRowState, };

export type LibraryTreeNodeKind = "directory" | "file";

export type LibraryTreeFileMediaClass = "audio" | "video" | "image" | "unsupported" | "none";

export type LibraryTreePresenceState = "present" | "missing" | "removed";

export type DirectoryPrimaryMediaState = { "kind": "unknown" } | { "kind": "hasPrimaryMediaDescendants" } | { "kind": "noPrimaryMediaDescendants" };

export type DirectoryImageMediaState = { "kind": "unknown" } | { "kind": "hasImageMediaDescendants" } | { "kind": "noImageMediaDescendants" };

export type DirectoryScanState = "pending" | "scanning" | "complete" | "failed" | "blocked";

export type SourceLifecycle = { sourceId: string, sourceClass: SourceClass, isUserVisible: boolean, mountStatus: SourceMountStatus, accessState: SourceAccessState, accessIssueKind?: SourceLifecycleIssueKind, scanPhase: SourceScanPhase, scanIssueKind?: SourceLifecycleIssueKind, lastScanStartedAtMs?: number, lastScanFinishedAtMs?: number, lastSuccessfulScanAtMs?: number, lastSeenAtMs?: number, updatedAtMs: number, };

export type AttachmentIdentityReadStatus = "ok" | "notFound" | "invalidRequest" | "readFailed";

export type AttachmentIdentity = { attachmentId: string, contentHashAlgorithm: string, contentHashValue: string, };

export type SourceFileAttachmentLink = { attachmentId: string, sourceFileId: string, sourceId: string, contentHashAlgorithm: string, contentHashValue: string, fileKind: ContentsFileKind, linkStatus: SourceFileAttachmentLinkStatus, createdAtMs: number, updatedAtMs: number, };

export type SourceFileAttachmentLinkStatus = "current" | "stale";

export type SourceAttachmentSummary = { sourceId: string, currentLinksCount: number, staleLinksCount: number, sourceFilesWithCurrentBlake3FactsCount: number, sourceFilesWithAttachmentLinksCount: number, sourceFilesMissingAttachmentLinksCount: number, unmaterializedBlake3FactsCount: number, };

export type ContentsResult = { state: ContentsState, scope: ContentsScope, policy: ContentsReadPolicy, recursion: ContentsRecursion, rows: Array<ContentsFileRow>, coverage: ContentsCoverage, nextCursor?: string, detail?: string, };

export type ContentsState = "ready" | "empty" | "partial" | "sourceUnavailable" | "locationMissing" | "blocked" | "failed" | "policyConflict" | "cursorInvalid";

export type ContentsCoverage = { state: ContentsCoverageState, recursiveScopeComplete: boolean, emptyResultAuthoritative: boolean, detail?: string, };

export type ContentsCoverageState = "complete" | "pending" | "scanning" | "blocked" | "failed" | "sourceUnavailable" | "locationMissing" | "incomplete";

export type ContentsFileRow = { id: string, sourceId: string, sourceFileId: string, parentDirectoryId: string | null, label: string, relativePath?: string, fileName: string, mediaClass: ContentsMediaClass, fileKind: ContentsFileKind, presence: ContentsPresenceState, availabilityState?: LibraryAssetAvailabilityState, primaryMedia?: PrimaryMediaSummary, updatedAtMs?: number, };

export type PrimaryMediaSummary = { origin: ContentsRowOrigin, primaryMediaCandidateId: string | null, attachmentId: string | null, contentHashAlgorithm: string | null, contentHashValue: string | null, evidenceSourceFileId: string | null, mediaKind: string | null, mimeType: string | null, libraryAssetId: string | null, rowVersion: string | null, primarySourceFileId: string | null, title: string | null, artist: string | null, album: string | null, durationMs: number | null, sampleRateHz: number | null, channels: number | null, bitDepth: number | null, codec: string | null, musicalKey: string | null, tempoBpm: number | null, waveformQualityCurrent: number | null, waveformQualityTarget: number | null, stemsStateSummary: LibraryAssetStemsStateSummary | null, prepReadinessSummary: LibraryAssetPrepReadinessSummary | null, };

export type ContentsRowOrigin = "libraryAsset" | "sourceFile" | "primaryMediaCandidate";

export type ContentsMediaClass = "audio" | "video" | "image" | "unsupported";

export type ContentsFileKind = "audio" | "video" | "image" | "cueSheet" | "logDoc" | "textDoc" | "archive" | "other" | "unknown";

export type ContentsPresenceState = "present" | "missing" | "removed";

export type LibraryBrowserWindow = { offset: number, limit: number, totalRows: number, rows: Array<LibraryAssetBrowserRow>, };

export type LibraryAssetBrowserRow = { libraryAssetId: string, rowVersion: string, primarySourceFileId: string | null, scopedSourceFileId: string | null, sourceId: string | null, relativePath: string | null, fileName: string | null, availabilityState: LibraryAssetAvailabilityState, title: string | null, artist: string | null, album: string | null, durationMs: number | null, musicalKey: string | null, tempoBpm: number | null, 
/**
 * Browse-facing summaries derived by projection rebuild logic from
 * capability/artifact state; they are not canonical authority.
 */
waveformQualityCurrent: number | null, waveformQualityTarget: number | null, stemsStateSummary: LibraryAssetStemsStateSummary | null, prepReadinessSummary: LibraryAssetPrepReadinessSummary, updatedAtMs: number, };

export type LibraryAssetAvailabilityState = "available" | "unavailable" | "degraded";

export type LibraryAssetStemsStateSummary = "missing" | "queued" | "leased" | "ready" | "stale" | "blocked" | "failed";

export type LibraryAssetPrepReadinessSummary = "notRequired" | "ready" | "preparing" | "underprepared" | "blocked" | "failed";

export type LibraryAssetPreparationDetail = { libraryAssetId: string, aggregateReadinessSummary: LibraryAssetPrepReadinessSummary, groups: Array<LibraryAssetPreparationDetailGroup>, };

export type LibraryAssetPreparationDetailGroup = { groupKey: LibraryAssetPreparationDetailGroupKey, rows: Array<LibraryAssetPreparationDetailRow>, };

export type LibraryAssetPreparationDetailGroupKey = "requiredFacts" | "requiredStructures" | "requiredArtifacts" | "onDemandCapabilities";

export type LibraryAssetPreparationDetailRow = { capabilityKey: LibraryAssetPreparationCapabilityKey, label: string, requirementClass: LibraryAssetPreparationRequirementClass, outcomeKind: LibraryAssetPreparationOutcomeKind, workState: LibraryAssetPreparationWorkState, outcomeState: LibraryAssetPreparationOutcomeState, satisfactionState: LibraryAssetPreparationSatisfactionState, displayValueSummary: string | null, targetSummary: string | null, explanationSummary: string | null, artifactCoverageState: LibraryAssetPreparationArtifactCoverageState | null, progress: LibraryAssetPreparationProgress | null, };

export type LibraryAssetPreparationCapabilityKey = "bpm" | "musicalKey" | "beatgrid" | "waveform" | "stems";

export type LibraryAssetPreparationRequirementClass = "required" | "onDemand";

export type LibraryAssetPreparationOutcomeKind = "fact" | "structure" | "artifact";

export type LibraryAssetPreparationWorkState = "none" | "notRequested" | "queued" | "active" | "blocked" | "failed";

export type LibraryAssetPreparationOutcomeState = "missing" | "provisional" | "ready" | "stale";

export type LibraryAssetPreparationSatisfactionState = "satisfied" | "unsatisfied";

export type LibraryAssetPreparationArtifactCoverageState = "none" | "previewReady" | "overviewReady" | "refinementAvailable" | "stale";

export type LibraryAssetPreparationProgress = { "type": "indeterminate", activeStage: string | null, } | { "type": "boundedStage", activeStage: string | null, completedUnits: number, totalUnits: number, fraction: number, };

export type LibraryAssetWaveformOverview = { sourceProfileKey: string, sourceQualityCurrent: number | null, capabilityState: LibraryAssetWaveformOverviewCapabilityState, amplitudeScale: LibraryAssetWaveformOverviewAmplitudeScale, bucketCount: number, durationMs: number | null, sourceSampleCount: number | null, samplesPerBucket: number | null, buckets: Array<LibraryAssetWaveformOverviewBucket>, acceptedArtifactId: string, basisFingerprint: string, capabilityUpdatedAtMs: number, artifactCreatedAtMs: number, };

export type LibraryAssetWaveformOverviewBucket = { minAmplitudeI16: number, maxAmplitudeI16: number, };

export type LibraryAssetWaveformOverviewCapabilityState = "ready" | "stale";

export type LibraryAssetWaveformOverviewAmplitudeScale = "signedI16";

export type HashSourceFilesBlake3Outcome = { sourceFileId: string, sourceId: string, relativePath: string, status: HashSourceFilesBlake3OutcomeStatus, };

export type HashSourceFilesBlake3OutcomeStatus = { "type": "hashed", "payload": HashSourceFilesBlake3HashedOutcome } | { "type": "skipped", "payload": HashSourceFilesBlake3SkippedOutcome } | { "type": "failed", "payload": HashSourceFilesBlake3FailedOutcome };

export type HashSourceFilesBlake3HashedOutcome = { contentHashAlgorithm: string, contentHashValue: string, acceptedArtifactId: string, workItemId: string, };

export type HashSourceFilesBlake3SkippedOutcome = { reason: HashSourceFilesBlake3SkipReason, };

export type HashSourceFilesBlake3FailedOutcome = { failure: HashSourceFilesBlake3FileFailure, };

export type HashSourceFilesBlake3SkipReason = "workAlreadyActive";

export type HashSourceFilesBlake3SourceFailure = { "type": "sourceNotFound" } | { "type": "sourceUnavailable", "payload": HashSourceFilesBlake3SourceUnavailableFailure } | { "type": "sourceRootMissing", "payload": HashSourceFilesBlake3SourceRootMissingFailure } | { "type": "sourceRootBlocked", "payload": HashSourceFilesBlake3SourceRootBlockedFailure };

export type HashSourceFilesBlake3SourceUnavailableFailure = { mountStatus?: SourceMountStatus, accessState?: SourceAccessState, accessIssueKind?: SourceLifecycleIssueKind, };

export type HashSourceFilesBlake3SourceRootMissingFailure = { detail?: string, };

export type HashSourceFilesBlake3SourceRootBlockedFailure = { accessIssueKind?: SourceLifecycleIssueKind, detail?: string, };

export type HashSourceFilesBlake3FileFailure = { "type": "sourceFileNotFound" } | { "type": "sourceFileUnavailable", "payload": HashSourceFilesBlake3SourceFileUnavailableFailure } | { "type": "sourceRootUnavailable", "payload": HashSourceFilesBlake3SourceUnavailableFailure } | { "type": "sourceRootMissing", "payload": HashSourceFilesBlake3SourceRootMissingFailure } | { "type": "sourceRootBlocked", "payload": HashSourceFilesBlake3SourceRootBlockedFailure } | { "type": "invalidRelativePath", "payload": HashSourceFilesBlake3InvalidRelativePathFailure } | { "type": "sourceFilePathEscapesRoot" } | { "type": "physicalFileMissing" } | { "type": "physicalFileBlocked", "payload": HashSourceFilesBlake3IoFailure } | { "type": "fileOpen", "payload": HashSourceFilesBlake3IoFailure } | { "type": "fileRead", "payload": HashSourceFilesBlake3IoFailure } | { "type": "basisChanged" } | { "type": "storeFailure" };

export type HashSourceFilesBlake3SourceFileUnavailableFailure = { presenceState: string, };

export type HashSourceFilesBlake3InvalidRelativePathFailure = { reason: string, };

export type HashSourceFilesBlake3IoFailure = { detail: string, };

export type SourceMaintenanceEffectiveLimits = { hashLimit: number, attachmentLimit: number, probeLimit: number, promotionLimit: number, identityCandidateLimit: number, };

export type SourceMaintenanceHashSummary = { effectiveLimit: number, hashedCount: number, skippedCount: number, failedCount: number, remainingCandidates: number, };

export type SourceMaintenanceAttachmentMaterializationSummary = { effectiveLimit: number, attachmentsCreated: number, attachmentsRefreshed: number, linksCreated: number, linksReplaced: number, linksRefreshed: number, skippedStaleFacts: number, skippedNoBlake3: number, skippedNoFacts: number, remainingCandidates: number, };

export type SourceMaintenanceProbeSummary = { effectiveLimit: number, probedCount: number, skippedCount: number, failedCount: number, remainingCandidates: number, };

export type SourceMaintenancePrimaryMediaPromotionSummary = { effectiveLimit: number, promotedCount: number, refreshedCount: number, skippedUnusableSource: number, skippedUnsupportedMediaKind: number, skippedNoFacts: number, skippedStaleFacts: number, skippedNoBlake3: number, skippedNoProbeFacts: number, skippedMissingAttachmentLink: number, skippedStaleAttachmentLink: number, remainingCandidates: number, };

export type SourceMaintenanceTrackIdentityCandidateSummary = { effectiveLimit: number, candidatesCreated: number, candidatesRefreshed: number, membersCreated: number, membersRefreshed: number, evidenceCreated: number, evidenceRefreshed: number, candidatesMarkedStale: number, skippedStalePrimaryMediaCandidates: number, remainingCandidates: number, };

export type SourceMaintenanceAttachmentLinkSummary = { currentLinksCount: number, staleLinksCount: number, sourceFilesWithCurrentBlake3FactsCount: number, sourceFilesWithAttachmentLinksCount: number, sourceFilesMissingAttachmentLinksCount: number, unmaterializedBlake3FactsCount: number, };

export type SourceMaintenanceLastRunSummary = { status: SourceMaintenanceRunStatus, hash: SourceMaintenanceHashSummary, attachmentMaterialization: SourceMaintenanceAttachmentMaterializationSummary, probe: SourceMaintenanceProbeSummary, primaryMediaPromotion: SourceMaintenancePrimaryMediaPromotionSummary, trackIdentityCandidates: SourceMaintenanceTrackIdentityCandidateSummary, remainingHashCandidates: number, remainingProbeCandidates: number, remainingPrimaryMediaPromotionCandidates: number, remainingTrackIdentityCandidateProductionCandidates: number, sourceFailure?: SourceMaintenanceSourceFailure, };

export type SourceMaintenanceRunStatus = "completed" | "partial" | "skipped" | "failed";

export type SourceMaintenanceSnapshotStatus = "idle" | "running" | "unavailable" | "blocked" | "failed";

export type SourceMaintenanceSourceFailure = { "type": "sourceNotFound" } | { "type": "sourceUnavailable", "payload": SourceMaintenanceSourceUnavailableFailure } | { "type": "sourceRootMissing", "payload": SourceMaintenanceSourceRootMissingFailure } | { "type": "sourceRootBlocked", "payload": SourceMaintenanceSourceRootBlockedFailure };

export type SourceMaintenanceSourceUnavailableFailure = { mountStatus?: SourceMountStatus, accessState?: SourceAccessState, accessIssueKind?: SourceLifecycleIssueKind, };

export type SourceMaintenanceSourceRootMissingFailure = { detail?: string, };

export type SourceMaintenanceSourceRootBlockedFailure = { accessIssueKind?: SourceLifecycleIssueKind, detail?: string, };

export type CommandOutcome = { "type": "success", "payload": CommandSuccessEnvelope } | { "type": "error", "payload": CommandErrorEnvelope };

export type CommandSuccessEnvelope = { reply: CommandReply, };

export type CommandErrorEnvelope = { error: ProtocolError, };

export type ProtocolError = { "type": "invalidRequest", "payload": { detail: string, } } | { "type": "durableStoreFailure", "payload": { detail: string, } } | { "type": "hostFailure", "payload": { detail: string, } };

export type LibraryBoundaryEvent = { "type": "sourceScanEvent", "payload": SourceScanEvent } | { "type": "maintainedSnapshotInvalidated", "payload": MaintainedSnapshotEvent };

export type SourceScanEvent = { eventSequence: number, occurredAtMs: number, kind: SourceScanEventKind, rootId: string, scanRunId: string, phase: ScanRunPhase, directoriesVisited: number, filesVisited: number, filesDiscovered: number, mediaCandidates: number, queuedWorkItems: number, detail: string | null, };

export type SourceScanEventKind = "sourceScanStarted" | "sourceScanProgressed" | "sourceScanCompleted" | "sourceScanFailed" | "sourceScanBlocked" | "sourceScanCancelled";

export type ScanRunPhase = "scanning" | "blocked" | "interrupted";

export type MaintainedSnapshotEvent = { eventSequence: number, occurredAtMs: number, invalidation: MaintainedSnapshotInvalidation, };

export type MaintainedSnapshotInvalidation = { scope: MaintainedSnapshotScope, revision: MaintainedSnapshotRevision | null, };

export type MaintainedSnapshotScopeRevision = { scope: MaintainedSnapshotScope, revision: MaintainedSnapshotRevision, };

export type MaintainedSnapshotScope = "navigationRows" | "libraryBrowser";

export type MaintainedSnapshotRevision = string;

export type LibraryBoundaryContract = { commandRequest: CommandRequest, commandOutcome: CommandOutcome, protocolError: ProtocolError, libraryBoundaryEvent: LibraryBoundaryEvent, };

