// @generated by cargo run -p xtask -- export-boundary-contract
// Source of truth: crates/library-boundary-protocol
// Do not edit by hand.

export type CommandRequest = { "type": "libraryBoundaryEvents", "payload": LibraryBoundaryEventStreamCommand } | { "type": "libraryRoots", "payload": LibraryRootCommand } | { "type": "sourceFileHash", "payload": SourceFileHashCommand } | { "type": "sourceMaintenance", "payload": SourceMaintenanceCommand } | { "type": "trackIdentityDecisions", "payload": TrackIdentityDecisionCommand } | { "type": "snapshotRead", "payload": SnapshotReadCommand };

export type LibraryBoundaryEventStreamCommand = { "type": "readAfter", "payload": ReadLibraryBoundaryEventsAfterRequest };

export type ReadLibraryBoundaryEventsAfterRequest = { 
/**
 * The last event sequence the caller has already observed.
 * `None` means start from the beginning.
 */
lastSeenEventSequence: number | null, maxEvents: number, };

export type LibraryRootCommand = { "type": "registerLocalRoot", "payload": RegisterLocalRootRequest } | { "type": "startRootScan", "payload": StartRootScanRequest } | { "type": "readLocalRoots", "payload": ReadLocalRootsRequest } | { "type": "unregisterLocalRoot", "payload": UnregisterLocalRootRequest } | { "type": "cancelRootScan", "payload": CancelRootScanRequest };

export type RegisterLocalRootRequest = { requestedPath: string, };

export type SourceRegistrationRootClass = "normalMusicRoot" | "broadDriveRoot" | "systemVolumeRoot" | "userProfileRoot" | "cloudBackedRoot" | "networkRoot" | "protectedRoot" | "indirectionRoot" | "unknownRoot";

export type RegisteredLocalRoot = { rootId: string, admittedRootPath: string, };

export type SourceRegistrationProposalRequired = { proposalId: string, rootClass: SourceRegistrationRootClass, requestedPath: string, resolvedPath: string | null, confirmationRequiredReason: string, suggestedRootPaths: Array<string>, };

export type SourceRegistrationRejected = { rootClass: SourceRegistrationRootClass, requestedPath: string, resolvedPath: string | null, rejectionReason: string, suggestedRootPaths: Array<string>, };

export type StartRootScanRequest = { rootId: string, };

export type CancelRootScanRequest = { scanRunId: string, };

export type CancelRootScanStatus = "accepted" | "notFound" | "alreadyTerminal" | "notCancelable";

export type ReadLocalRootsRequest = null;

export type UnregisterLocalRootRequest = { rootId: string, };

export type LocalRootAvailability = "available" | "unavailable";

export type LocalRoot = { rootId: string, admittedRootPath: string, availability: LocalRootAvailability, };

export type SourceFileHashCommand = { "type": "hashSourceFilesBlake3", "payload": HashSourceFilesBlake3Request };

export type HashSourceFilesBlake3Request = { sourceId: string, limit?: number, };

export type SourceMaintenanceCommand = { "type": "runSourceMaintenance", "payload": RunSourceMaintenanceRequest };

export type RunSourceMaintenanceRequest = { sourceId: string, hashLimit?: number, attachmentLimit?: number, probeLimit?: number, promotionLimit?: number, identityCandidateLimit?: number, identityDecisionLimit?: number, };

export type TrackIdentityDecisionCommand = { "type": "acceptTrackIdentityCandidate", "payload": AcceptTrackIdentityCandidateRequest } | { "type": "rejectTrackIdentityCandidate", "payload": RejectTrackIdentityCandidateRequest } | { "type": "deferTrackIdentityCandidate", "payload": DeferTrackIdentityCandidateRequest };

export type AcceptTrackIdentityCandidateRequest = { candidateId: string, reason?: string, };

export type RejectTrackIdentityCandidateRequest = { candidateId: string, reason?: string, };

export type DeferTrackIdentityCandidateRequest = { candidateId: string, reason?: string, };

export type SnapshotReadCommand = { "type": "readNavigationRows", "payload": ReadNavigationRowsRequest } | { "type": "loadNavigationRow", "payload": LoadNavigationRowRequest } | { "type": "loadNavigationRowByStableKey", "payload": LoadNavigationRowByStableKeyRequest } | { "type": "readLocalBrowseEntryPoints", "payload": ReadLocalBrowseEntryPointsRequest } | { "type": "readLocalBrowseItems", "payload": ReadLocalBrowseItemsRequest } | { "type": "readLibraryTreeChildren", "payload": ReadLibraryTreeChildrenRequest } | { "type": "readSourceLifecycle", "payload": ReadSourceLifecycleRequest } | { "type": "readSourceIntegrity", "payload": ReadSourceIntegrityRequest } | { "type": "readSourceMaintenance", "payload": ReadSourceMaintenanceRequest } | { "type": "readSourceFileAttachment", "payload": ReadSourceFileAttachmentRequest } | { "type": "readAttachmentSourceFiles", "payload": ReadAttachmentSourceFilesRequest } | { "type": "readSourceAttachmentSummary", "payload": ReadSourceAttachmentSummaryRequest } | { "type": "readTrackIdentityReviewCandidates", "payload": ReadTrackIdentityReviewCandidatesRequest } | { "type": "contentsRead", "payload": ContentsReadRequest } | { "type": "searchFilterRead", "payload": SearchFilterReadRequest };

export type ReadNavigationRowsRequest = { parentNavigationRowId: string | null, };

export type LoadNavigationRowRequest = { navigationRowId: string, };

export type LoadNavigationRowByStableKeyRequest = { stableKey: string, };

export type ReadLocalBrowseEntryPointsRequest = null;

export type LocalBrowseEntryPointKind = "systemDriveRoot" | "localDataVolumeRoot" | "removableVolumeRoot" | "userHome" | "desktop" | "downloads" | "music";

export type LocalBrowseEntryPointStatus = "resolving" | "available" | "unavailable" | "permissionBlocked" | "missing" | "unsupportedPlatform" | "duplicateOfAdmittedSource";

export type LocalBrowsePlatform = "windows" | "macos" | "linux" | "unsupported";

export type LocalBrowseOperation = { "kind": "browseChildren" } | { "kind": "chooseDescendant" } | { "kind": "requestSourceAdmission", requestKind: LocalBrowseSourceAdmissionRequestKind, resolvedPath: string, };

export type LocalBrowseSourceAdmissionRequestKind = "defaultMusicFolder" | "selectedDirectory" | "parentDirectory";

export type LocalBrowseProfile = "audio" | "playable" | "allFiles";

export type LocalBrowseEntryPointFailureCode = "unsupportedPlatform" | "knownFolderUnavailable" | "systemDriveUnavailable" | "volumeEnumerationUnavailable" | "metadataUnavailable";

export type ReadLocalBrowseItemsRequest = { entryPointKind: LocalBrowseEntryPointKind, resolvedRootPath: string, resolvedParentPath: string, profile: LocalBrowseProfile, offset: number, limit: number, };

export type LocalBrowseItemKind = "directory" | "mediaFile" | "unsupportedFile" | "rejectedRoot" | "inaccessible" | "unknown";

export type LocalBrowseItemStatus = "available" | "unavailable" | "permissionBlocked" | "missing" | "unsupportedPlatform" | "duplicateOfAdmittedSource" | "rejected" | "unknown";

export type LocalBrowseItemMediaRelevance = "mediaRelevant" | "companionMetadata" | "unsupported" | "unknown";

export type LocalBrowseItemFailureCode = "unsupportedPlatform" | "rootIdentityMismatch" | "rootPathUnavailable" | "parentPathUnavailable" | "parentMissing" | "parentNotDirectory" | "parentOutsideRoot" | "permissionDenied" | "metadataUnavailable" | "enumerationUnavailable" | "reparsePointSkipped" | "rejectedRoot" | "unknownFileType";

export type ReadLibraryTreeChildrenRequest = { entryPoint: LibraryTreeEntryPoint, parentSourceDirectoryId: string | null, rowPolicy?: LibraryTreeRowPolicy, offset: number, limit: number, };

export type NavigableChildScopeState = "unknown" | "hasNavigableChildScopes" | "noNavigableChildScopes";

export type ReadSourceLifecycleRequest = { sourceId: string, };

export type ReadSourceIntegrityRequest = { sourceId: string, };

export type ReadSourceMaintenanceRequest = { sourceId: string, };

export type SourceClass = "internal" | "externalMounted" | "removableMounted";

export type SourceMountStatus = "unknown" | "mounted" | "unmounted" | "ejectRequested" | "ejectPending";

export type SourceAccessState = "accessible" | "missing" | "blocked" | "unknown";

export type SourceLifecycleIssueKind = "missing" | "notDirectory" | "permissionDenied" | "privacyPermissionRequired" | "unavailableMount" | "resourceBusy" | "staleNetworkHandle" | "symlinkLoop" | "symlinkEscapeBlocked" | "unsupportedPath" | "invalidPath" | "ioInterrupted" | "timedOut" | "unknownIo";

export type SourceScanPhase = "idle" | "scanning" | "complete" | "partial" | "blocked" | "failed";

export type ReadSourceFileAttachmentRequest = { sourceFileId: string, };

export type ReadAttachmentSourceFilesRequest = { attachmentId: string, limit?: number, };

export type ReadSourceAttachmentSummaryRequest = { sourceId: string, };

export type ReadTrackIdentityReviewCandidatesRequest = { sourceId?: string, reviewState?: TrackIdentityReviewState, limit: number, };

export type ContentsReadRequest = { scope: ContentsScope, policy: ContentsReadPolicy, scopeDepth: ContentsScopeDepth, limit?: number, cursor?: string, };

export type SearchFilterReadRequest = { scope: SearchFilterScope, recursion: SearchFilterRecursion, textQuery?: string, targetKinds?: Array<SearchFilterResultKind>, filters: SearchFilterSet, sort: SearchFilterSort, limit?: number, cursor?: string, };

export type SearchFilterScope = { "type": "library" } | { "type": "source", "payload": { sourceId: string, } } | { "type": "sourceLocation", "payload": { sourceLocationId: string, } } | { "type": "directory", "payload": { sourceId: string, sourceDirectoryId: string, } };

export type SearchFilterRecursion = "immediate" | "recursive";

export type SearchFilterSort = "pathName" | "relevance";

export type SearchFilterResultKind = "source" | "sourceLocation" | "directory" | "sourceFile";

export type SearchFilterSet = { fileClasses?: Array<SearchFilterFileClass>, fileKinds?: Array<ContentsFileKind>, mediaRelevance?: Array<SearchFilterMediaRelevance>, presenceStates?: Array<ContentsPresenceState>, sourceAccessStates?: Array<SearchFilterSourceAccessState>, blake3?: SearchFilterEvidenceAvailability, probe?: SearchFilterEvidenceAvailability, attachmentLinkStates?: Array<SearchFilterAttachmentLinkState>, };

export type SearchFilterFileClass = "audio" | "video" | "image" | "unsupported" | "none";

export type SearchFilterSourceAccessState = "accessible" | "missing" | "blocked" | "unknown";

export type SearchFilterEvidenceAvailability = "hasCurrent" | "missingCurrent";

export type SearchFilterAttachmentLinkState = "current" | "stale" | "missing" | "notApplicable";

export type SearchFilterMediaRelevance = "audioWorkflow" | "playableMedia" | "explicitInventory" | "companionFile" | "notMediaRelevant";

export type SearchFilterIndexState = "ready" | "rebuilding" | "partial" | "failed" | "missing";

export type SearchFilterAuthorityLayer = "source" | "sourceLocation" | "sourceHierarchy" | "sourceFileInventory";

export type SearchFilterEvidenceCoverageState = "indexed" | "notApplicable";

export type SearchFilterMatchReason = "filter" | "exactLabel" | "labelPrefix" | "label" | "path" | "text";

export type ContentsScope = { "type": "source", "payload": { sourceId: string, } } | { "type": "sourceLocation", "payload": { sourceLocationId: string, } } | { "type": "directory", "payload": { sourceId: string, sourceDirectoryId: string, } };

export type ContentsReadPolicy = { "kind": "playableMediaBrowse" } | { "kind": "audioBrowse" } | { "kind": "sourceFileInventory", fileClasses: Array<ContentsFileClass>, } | { "kind": "playableMedia", mediaKinds: Array<PlayableMediaKind>, };

export type ContentsFileClass = "audio" | "video" | "image" | "unsupported";

export type PlayableMediaKind = "audio" | "video";

export type ContentsScopeDepth = "immediate" | "recursive";

export type CommandReply = { "type": "libraryBoundaryEvents", "payload": LibraryBoundaryEventStreamReply } | { "type": "libraryRoots", "payload": LibraryRootReply } | { "type": "sourceFileHash", "payload": SourceFileHashReply } | { "type": "sourceMaintenance", "payload": SourceMaintenanceReply } | { "type": "trackIdentityDecisions", "payload": TrackIdentityDecisionReply } | { "type": "snapshotRead", "payload": SnapshotReadReply };

export type LibraryBoundaryEventStreamReply = { "type": "readAfter", "payload": ReadLibraryBoundaryEventsAfterReply };

export type ReadLibraryBoundaryEventsAfterReply = { events: Array<LibraryBoundaryEvent>, 
/**
 * The cursor the consumer should pass as `lastSeenEventSequence` in
 * the next read-after call.  It is the event sequence of the last
 * event delivered in this reply, or the previously supplied
 * `lastSeenEventSequence` when no new events were returned, or
 * `None` when no events have been published yet.
 */
latestEventSequence: number | null, 
/**
 * The earliest sequence still retained in the event ring buffer.
 * If the caller asks for events after a sequence lower than this,
 * some events have been compacted away.
 */
earliestRetainedSequence: number | null, 
/**
 * True when the caller's `lastSeenEventSequence` is older than the
 * earliest retained event, meaning events were compacted away.
 */
gapDetected: boolean, };

export type LibraryRootReply = { "type": "registerLocalRoot", "payload": RegisterLocalRootReply } | { "type": "startRootScan", "payload": StartRootScanReply } | { "type": "readLocalRoots", "payload": ReadLocalRootsReply } | { "type": "unregisterLocalRoot", "payload": UnregisterLocalRootReply } | { "type": "cancelRootScan", "payload": CancelRootScanReply };

export type RegisterLocalRootReply = { "type": "registered", "payload": RegisteredLocalRoot } | { "type": "proposalRequired", "payload": SourceRegistrationProposalRequired } | { "type": "rejected", "payload": SourceRegistrationRejected };

export type StartRootScanReply = { scanRunId: string, };

export type CancelRootScanReply = { status: CancelRootScanStatus, };

export type ReadLocalRootsReply = { roots: Array<LocalRoot>, };

export type UnregisterLocalRootReply = { unregistered: boolean, };

export type SourceFileHashReply = { "type": "hashSourceFilesBlake3", "payload": HashSourceFilesBlake3Reply };

export type HashSourceFilesBlake3Reply = { effectiveLimit: number, outcomes: Array<HashSourceFilesBlake3Outcome>, hashedCount: number, skippedCount: number, failedCount: number, remainingCandidates: number, sourceFailure?: HashSourceFilesBlake3SourceFailure, };

export type SourceMaintenanceReply = { "type": "runSourceMaintenance", "payload": RunSourceMaintenanceReply };

export type RunSourceMaintenanceReply = { sourceId: string, status: SourceMaintenanceRunStatus, effectiveLimits: SourceMaintenanceEffectiveLimits, hash: SourceMaintenanceHashSummary, attachmentMaterialization: SourceMaintenanceAttachmentMaterializationSummary, probe: SourceMaintenanceProbeSummary, playableMediaPromotion: SourceMaintenancePlayableMediaPromotionSummary, trackIdentityCandidates: SourceMaintenanceTrackIdentityCandidateSummary, trackIdentityDecisions: SourceMaintenanceTrackIdentityDecisionSummary, remainingHashCandidates: number, remainingProbeCandidates: number, remainingPlayableMediaPromotionCandidates: number, remainingTrackIdentityCandidateProductionCandidates: number, remainingTrackIdentityDecisionProductionCandidates: number, attachmentLinks?: SourceMaintenanceAttachmentLinkSummary, sourceFailure?: SourceMaintenanceSourceFailure, };

export type TrackIdentityDecisionReply = { "type": "acceptTrackIdentityCandidate", "payload": TrackIdentityDecisionCommandResult } | { "type": "rejectTrackIdentityCandidate", "payload": TrackIdentityDecisionCommandResult } | { "type": "deferTrackIdentityCandidate", "payload": TrackIdentityDecisionCommandResult };

export type TrackIdentityDecisionCommandResult = { "type": "written", "payload": TrackIdentityDecisionCommandSuccess } | { "type": "failed", "payload": TrackIdentityDecisionCommandFailure };

export type TrackIdentityDecisionCommandSuccess = { decisionId: string, candidateId: string, decisionState: TrackIdentityDecisionState, decisionSource: string, evidenceSnapshotCount: number, decisionCreated: boolean, effectiveDecision: TrackIdentityEffectiveDecisionSummary, };

export type TrackIdentityDecisionCommandFailure = { "type": "candidateNotFound" } | { "type": "candidateStaleForAccept" } | { "type": "noCurrentEvidenceForAccept" } | { "type": "noSourceScopeForDecision" };

export type TrackIdentityDecisionState = "accepted" | "rejected" | "deferred";

export type TrackIdentityEffectiveDecisionSummary = { effectiveDecisionId?: string | null, effectiveDecisionState?: TrackIdentityDecisionState, effectiveDecisionSource?: string, effectiveDecisionCurrentStatus: TrackIdentityEffectiveDecisionCurrentStatus, effectiveDecisionPrecedence: TrackIdentityEffectiveDecisionPrecedence, userBlockingDecisionState: TrackIdentityUserBlockingDecisionState, maskedSystemDecisionId?: string | null, };

export type TrackIdentityEffectiveDecisionCurrentStatus = "current" | "stale" | "noCurrentDecision";

export type TrackIdentityEffectiveDecisionPrecedence = "user" | "system" | "none";

export type TrackIdentityUserBlockingDecisionState = "none" | "rejected" | "deferred";

export type SnapshotReadReply = { "type": "navigationRows", "payload": ReadNavigationRowsReply } | { "type": "navigationRow", "payload": LoadNavigationRowReply } | { "type": "navigationRowByStableKey", "payload": LoadNavigationRowByStableKeyReply } | { "type": "localBrowseEntryPoints", "payload": ReadLocalBrowseEntryPointsReply } | { "type": "localBrowseItems", "payload": ReadLocalBrowseItemsReply } | { "type": "libraryTreeChildren", "payload": ReadLibraryTreeChildrenReply } | { "type": "sourceLifecycle", "payload": ReadSourceLifecycleReply } | { "type": "sourceIntegrity", "payload": ReadSourceIntegrityReply } | { "type": "sourceMaintenance", "payload": ReadSourceMaintenanceReply } | { "type": "sourceFileAttachment", "payload": ReadSourceFileAttachmentReply } | { "type": "attachmentSourceFiles", "payload": ReadAttachmentSourceFilesReply } | { "type": "sourceAttachmentSummary", "payload": ReadSourceAttachmentSummaryReply } | { "type": "trackIdentityReviewCandidates", "payload": ReadTrackIdentityReviewCandidatesReply } | { "type": "contents", "payload": ContentsReadReply } | { "type": "searchFilter", "payload": SearchFilterReadReply };

export type ReadNavigationRowsReply = { rows: Array<NavigationRow>, };

export type LoadNavigationRowReply = { row: NavigationRow | null, };

export type LoadNavigationRowByStableKeyReply = { row: NavigationRow | null, };

export type ReadLocalBrowseEntryPointsReply = { status: LocalBrowseEntryPointsReadStatus, entries: Array<LocalBrowseEntryPoint>, failure: LocalBrowseEntryPointFailure | null, };

export type LocalBrowseEntryPointsReadStatus = "complete" | "partialFailure" | "failed" | "unsupportedPlatform";

export type LocalBrowseEntryPoint = { identity: LocalBrowseEntryPointIdentity, displayName: string, status: LocalBrowseEntryPointStatus, platform: LocalBrowsePlatform, availableOperations: Array<LocalBrowseOperation>, failure: LocalBrowseEntryPointFailure | null, };

export type LocalBrowseEntryPointIdentity = { entryPointKind: LocalBrowseEntryPointKind, resolvedPath: string | null, };

export type LocalBrowseEntryPointFailure = { code: LocalBrowseEntryPointFailureCode, detail: string, };

export type ReadLocalBrowseItemsReply = { status: LocalBrowseItemsReadStatus, windowIdentity: LocalBrowseWindowIdentity, offset: number, limit: number, totalItems: number, items: Array<LocalBrowseItem>, failure: LocalBrowseItemFailure | null, };

export type LocalBrowseItemsReadStatus = "complete" | "partialFailure" | "failed" | "unsupportedPlatform" | "missing" | "permissionBlocked" | "unavailable";

export type LocalBrowseWindowIdentity = { entryPointKind: LocalBrowseEntryPointKind, resolvedRootPath: string, resolvedParentPath: string, };

export type LocalBrowseItem = { identity: LocalBrowseItemIdentity, itemKind: LocalBrowseItemKind, displayName: string, status: LocalBrowseItemStatus, platform: LocalBrowsePlatform, fileKind: ContentsFileKind | null, mediaRelevance: LocalBrowseItemMediaRelevance | null, availableOperations: Array<LocalBrowseOperation>, failure: LocalBrowseItemFailure | null, };

export type LocalBrowseItemIdentity = { entryPointKind: LocalBrowseEntryPointKind, resolvedRootPath: string, resolvedItemPath: string, };

export type LocalBrowseItemFailure = { code: LocalBrowseItemFailureCode, detail: string, };

export type ReadLibraryTreeChildrenReply = { window: LibraryTreeWindow | null, };

export type ReadSourceLifecycleReply = { lifecycle: SourceLifecycle | null, };

export type ReadSourceIntegrityReply = { sourceId: string, sourceAvailability: SourceIntegrityAvailability, coverageIntegrity: SourceIntegrityCoverage, inventory?: SourceIntegrityInventory, evidenceAndMaintenance: SourceIntegrityEvidenceAndMaintenance, attachmentIntegrity?: SourceIntegrityAttachmentIntegrity, runtimeMaintenance: SourceIntegrityRuntimeMaintenance, };

export type ReadSourceMaintenanceReply = { sourceId: string, status: SourceMaintenanceSnapshotStatus, remainingHashCandidates: number, remainingProbeCandidates: number, remainingPlayableMediaPromotionCandidates: number, remainingTrackIdentityCandidateProductionCandidates: number, remainingTrackIdentityDecisionProductionCandidates: number, attachmentLinks?: SourceMaintenanceAttachmentLinkSummary, sourceFailure?: SourceMaintenanceSourceFailure, lastRun?: SourceMaintenanceLastRunSummary, };

export type ReadSourceFileAttachmentReply = { status: AttachmentIdentityReadStatus, attachmentLink?: SourceFileAttachmentLink, };

export type ReadAttachmentSourceFilesReply = { status: AttachmentIdentityReadStatus, attachment?: AttachmentIdentity, sourceFileLinks: Array<SourceFileAttachmentLink>, summary?: AttachmentSourceFilesSummary, effectiveLimit: number, remainingSourceFileLinks: number, };

export type ReadSourceAttachmentSummaryReply = { status: AttachmentIdentityReadStatus, summary?: SourceAttachmentSummary, };

export type ReadTrackIdentityReviewCandidatesReply = { status: TrackIdentityReviewReadStatus, candidates: Array<TrackIdentityReviewCandidate>, };

export type TrackIdentityReviewReadStatus = "ok" | "sourceNotFound";

export type TrackIdentityReviewCandidate = { candidateId: string, candidateKind: string, candidateEvidenceBasis: string, candidateStatus: TrackIdentityReviewCandidateStatus, evidenceKeyAlgorithm: string, evidenceKeyValue: string, evidenceSummary: TrackIdentityReviewEvidenceSummary, sourceSummary: TrackIdentityReviewSourceSummary, reviewState: TrackIdentityReviewState, effectiveDecision?: TrackIdentityReviewDecision, createdAtMs: number, updatedAtMs: number, };

export type TrackIdentityReviewCandidateStatus = "active" | "stale" | "superseded";

export type TrackIdentityReviewDecision = { decisionId: string, decisionState: TrackIdentityDecisionState, decisionSource: string, decisionBasis: string, currentStatus: TrackIdentityEffectiveDecisionCurrentStatus, createdAtMs: number, userBlockingDecisionState: TrackIdentityUserBlockingDecisionState, maskedSystemDecisionId?: string | null, };

export type TrackIdentityReviewEvidenceSummary = { memberCount: number, evidenceCount: number, currentEvidenceCount: number, };

export type TrackIdentityReviewSourceSummary = { sourceCount: number, sourceSamples: Array<TrackIdentityReviewSourceSample>, };

export type TrackIdentityReviewSourceSample = { sourceId: string, displayName: string, };

export type TrackIdentityReviewState = "needsUserDecision" | "systemAccepted" | "userAccepted" | "userRejected" | "userDeferred" | "staleDecision";

export type ContentsReadReply = { result: ContentsResult, };

export type SearchFilterReadReply = { result: SearchFilterResult, };

export type NavigationRow = { navigationRowId: string, stableKey: string, parentNavigationRowId: string | null, family: NavigationRowFamily | null, rowKind: NavigationRowKind, displayName: string, siblingPosition: number, selectable: boolean, selectorKind: NavigationRowSelectorKind | null, selectorPayload: string | null, updatedAtMs: number, rowVersion: string, };

export type NavigationRowFamily = "views" | "sources";

export type NavigationRowKind = "view" | "source" | "locationGroup" | "location";

export type NavigationRowSelectorKind = "allMedia" | "allAudio" | "allVideos" | "recentlyAdded" | "source" | "sourceLocation";

export type LibraryTreeEntryPoint = { "type": "source", "payload": { sourceId: string, } } | { "type": "sourceLocation", "payload": { sourceLocationId: string, } };

export type LibraryTreeWindow = { entryPoint: LibraryTreeEntryPoint, parentSourceDirectoryId: string | null, offset: number, limit: number, totalRows: number, rows: Array<LibraryTreeNode>, coverage: LibraryTreeCoverage, };

export type LibraryTreeCoverage = { state: LibraryTreeCoverageState, subtreeCoverageComplete: boolean, emptyResultAuthoritative: boolean, detail: string | null, };

export type LibraryTreeCoverageState = "complete" | "pending" | "scanning" | "blocked" | "failed" | "sourceUnavailable" | "locationMissing";

export type LibraryTreeNode = { nodeKind: LibraryTreeNodeKind, sourceId: string, sourceDirectoryId: string | null, sourceFileId: string | null, parentSourceDirectoryId: string | null, relativePath: string, displayName: string, fileClass?: LibraryTreeFileClass, presenceState: LibraryTreePresenceState, sizeBytes: number | null, modifiedAtNs: number | null, updatedAtMs: number, hasChildDirectories?: boolean, directoryPlayableMediaState?: DirectoryPlayableMediaState, directoryImageMediaState?: DirectoryImageMediaState, directoryScanState?: DirectoryScanState, navigableChildScopeState?: NavigableChildScopeState, };

export type LibraryTreeNodeKind = "directory" | "file";

export type LibraryTreeFileClass = "audio" | "video" | "image" | "unsupported" | "none";

export type LibraryTreePresenceState = "present" | "missing" | "removed";

export type DirectoryPlayableMediaState = { "kind": "unknown" } | { "kind": "hasPlayableMediaDescendants" } | { "kind": "noPlayableMediaDescendants" };

export type DirectoryImageMediaState = { "kind": "unknown" } | { "kind": "hasImageMediaDescendants" } | { "kind": "noImageMediaDescendants" };

export type DirectoryScanState = "pending" | "scanning" | "complete" | "failed" | "blocked";

export type SourceLifecycle = { sourceId: string, sourceClass: SourceClass, isUserVisible: boolean, mountStatus: SourceMountStatus, accessState: SourceAccessState, accessIssueKind?: SourceLifecycleIssueKind, scanPhase: SourceScanPhase, scanIssueKind?: SourceLifecycleIssueKind, lastScanStartedAtMs?: number, lastScanFinishedAtMs?: number, lastSuccessfulScanAtMs?: number, lastSeenAtMs?: number, updatedAtMs: number, };

export type SourceIntegrityAvailability = { state: SourceIntegrityAvailabilityState, lifecycle?: SourceLifecycle, sourceFailure?: SourceMaintenanceSourceFailure, };

export type SourceIntegrityAvailabilityState = "notFound" | "mounted" | "unavailable" | "missing" | "blocked" | "partial" | "unknown";

export type SourceIntegrityCoverage = { state: ContentsScopeCoverageState, subtreeCoverageComplete: boolean, emptyResultAuthoritative: boolean, totalDirectoriesCount: number, missingDirectoriesCount: number, pendingDirectoriesCount: number, scanningDirectoriesCount: number, blockedDirectoriesCount: number, failedDirectoriesCount: number, };

export type SourceIntegrityInventory = { countsByPresenceState: Array<SourceIntegrityPresenceCount>, countsByFileClass: Array<SourceIntegrityFileClassCount>, countsByFileKind: Array<SourceIntegrityFileKindCount>, mediaRelevantFilesCount: number, presentMediaRelevantFilesCount: number, };

export type SourceIntegrityFileClass = "audio" | "video" | "image" | "unsupported" | "none";

export type SourceIntegrityPresenceCount = { presenceState: ContentsPresenceState, count: number, };

export type SourceIntegrityFileClassCount = { fileClass: SourceIntegrityFileClass, count: number, };

export type SourceIntegrityFileKindCount = { fileKind: ContentsFileKind, count: number, };

export type SourceIntegrityEvidenceAndMaintenance = { remainingHashCandidates: number, remainingProbeCandidates: number, remainingPlayableMediaPromotionCandidates: number, remainingTrackIdentityCandidateProductionCandidates: number, remainingTrackIdentityDecisionProductionCandidates: number, sourceFailure?: SourceMaintenanceSourceFailure, };

export type SourceIntegrityAttachmentIntegrity = { currentLinksCount: number, staleLinksCount: number, missingLinksCount: number, sourceFilesWithCurrentBlake3ObservationsCount: number, sourceFilesWithAttachmentLinksCount: number, unmaterializedBlake3ObservationsCount: number, };

export type SourceIntegrityRuntimeMaintenance = { state: SourceIntegrityRuntimeMaintenanceState, lastRun?: SourceMaintenanceLastRunSummary, };

export type SourceIntegrityRuntimeMaintenanceState = "idle" | "running";

export type AttachmentIdentityReadStatus = "ok" | "notFound" | "invalidRequest" | "readFailed";

export type AttachmentIdentity = { attachmentId: string, contentHashAlgorithm: string, contentHashValue: string, };

export type AttachmentSourceFileOccurrenceStatus = "available" | "sourceUnavailable" | "sourceMissing" | "sourceBlocked" | "fileMissing" | "fileRemoved" | "unknown";

export type SourceFileAttachmentLink = { sourceFileAttachmentLinkId: string, attachmentId: string, sourceFileId: string, sourceId: string, contentHashAlgorithm: string, contentHashValue: string, sourceDisplayName: string, sourceClass: SourceClass, parentSourceDirectoryId?: string, name: string, relativePath: string, sizeBytes?: number, mtimeNs?: number, fileKind: ContentsFileKind, fileClass: SearchFilterFileClass, presenceState: ContentsPresenceState, hasCurrentBlake3Observation: boolean, linkStatus: SourceFileAttachmentLinkStatus, sourceMountStatus: SourceMountStatus, sourceAccessState: SourceAccessState, sourceAccessIssueKind?: SourceLifecycleIssueKind, sourceScanPhase: SourceScanPhase, sourceAvailabilityState: SourceIntegrityAvailabilityState, occurrenceStatus: AttachmentSourceFileOccurrenceStatus, createdAtMs: number, updatedAtMs: number, sourceFileUpdatedAtMs: number, };

export type SourceFileAttachmentLinkStatus = "current" | "stale";

export type AttachmentSourceFilesSummary = { totalOccurrenceCount: number, availableOccurrenceCount: number, unavailableOccurrenceCount: number, currentLinkOccurrenceCount: number, staleLinkOccurrenceCount: number, distinctSourceCount: number, hasMultipleOccurrences: boolean, };

export type SourceAttachmentSummary = { sourceId: string, currentLinksCount: number, staleLinksCount: number, sourceFilesWithCurrentBlake3ObservationsCount: number, sourceFilesWithAttachmentLinksCount: number, sourceFilesMissingAttachmentLinksCount: number, unmaterializedBlake3ObservationsCount: number, };

export type ContentsResult = { state: ContentsState, scope: ContentsScope, policy: ContentsReadPolicy, scopeDepth: ContentsScopeDepth, rows: Array<ContentsFileRow>, scopeCoverage: ContentsScopeCoverage, hasPolicyOmittedRows: boolean, nextCursor?: string, detail?: string, };

export type SearchFilterResult = { state: SearchFilterState, queryIdentity: SearchFilterQueryIdentity, indexGeneration: string, indexState: SearchFilterIndexState, rows: Array<SearchFilterResultRow>, nextCursor?: string, detail?: string, };

export type SearchFilterState = "ready" | "empty" | "partial" | "cursorInvalid" | "unsupported";

export type SearchFilterQueryIdentity = { scope: SearchFilterScope, recursion: SearchFilterRecursion, textQuery?: string, targetKinds: Array<SearchFilterResultKind>, filters: SearchFilterSet, sort: SearchFilterSort, pageSize: number, indexGeneration: string, };

export type SearchFilterResultRow = { resultKind: SearchFilterResultKind, authorityLayer: SearchFilterAuthorityLayer, stableKey: string, sourceId: string | null, sourceLocationId: string | null, sourceDirectoryId: string | null, parentSourceDirectoryId: string | null, sourceFileId: string | null, displayLabel: string, displayPath?: string, relativePath?: string, fileClass?: SearchFilterFileClass, fileKind?: ContentsFileKind, mediaRelevance?: SearchFilterMediaRelevance, presenceState?: ContentsPresenceState, sourceAccessState?: SearchFilterSourceAccessState, sourceScanPhase?: SourceScanPhase, hasCurrentBlake3: boolean, hasCurrentProbe: boolean, attachmentLinkState: SearchFilterAttachmentLinkState, attachmentId: string | null, contentHashAlgorithm?: string, contentHashValue?: string, evidenceCoverageState: SearchFilterEvidenceCoverageState, matchReason: SearchFilterMatchReason, updatedAtMs: number, };

export type ContentsState = "ready" | "empty" | "partial" | "sourceUnavailable" | "locationMissing" | "blocked" | "failed" | "policyConflict" | "cursorInvalid";

export type ContentsScopeCoverage = { state: ContentsScopeCoverageState, subtreeCoverageComplete: boolean, emptyResultAuthoritative: boolean, detail?: string, };

export type ContentsScopeCoverageState = "complete" | "pending" | "scanning" | "blocked" | "failed" | "sourceUnavailable" | "locationMissing" | "incomplete";

export type ContentsFileRow = { id: string, sourceId: string, sourceFileId: string, parentDirectoryId: string | null, label: string, relativePath?: string, fileName: string, fileClass: ContentsFileClass, fileKind: ContentsFileKind, presence: ContentsPresenceState, playableMedia?: PlayableMedia, updatedAtMs?: number, };

export type PlayableMedia = { playableMediaId: string, attachmentId: string, contentHashAlgorithm: string, contentHashValue: string, evidenceSourceFileId: string, mediaKind: string, mimeType: string | null, durationMs: number | null, sampleRateHz: number | null, channels: number | null, bitDepth: number | null, codec: string | null, };

export type ContentsFileKind = "audio" | "video" | "image" | "cueSheet" | "logDoc" | "textDoc" | "archive" | "other" | "unknown";

export type ContentsPresenceState = "present" | "missing" | "removed";

export type HashSourceFilesBlake3Outcome = { sourceFileId: string, sourceId: string, relativePath: string, status: HashSourceFilesBlake3OutcomeStatus, };

export type HashSourceFilesBlake3OutcomeStatus = { "type": "hashed", "payload": HashSourceFilesBlake3HashedOutcome } | { "type": "skipped", "payload": HashSourceFilesBlake3SkippedOutcome } | { "type": "failed", "payload": HashSourceFilesBlake3FailedOutcome };

export type HashSourceFilesBlake3HashedOutcome = { contentHashAlgorithm: string, contentHashValue: string, acceptedArtifactId: string, workItemId: string, };

export type HashSourceFilesBlake3SkippedOutcome = { reason: HashSourceFilesBlake3SkipReason, };

export type HashSourceFilesBlake3FailedOutcome = { failure: HashSourceFilesBlake3FileFailure, };

export type HashSourceFilesBlake3SkipReason = "workAlreadyActive";

export type HashSourceFilesBlake3SourceFailure = { "type": "sourceNotFound" } | { "type": "sourceUnavailable", "payload": HashSourceFilesBlake3SourceUnavailableFailure } | { "type": "sourceRootMissing", "payload": HashSourceFilesBlake3SourceRootMissingFailure } | { "type": "sourceRootBlocked", "payload": HashSourceFilesBlake3SourceRootBlockedFailure };

export type HashSourceFilesBlake3SourceUnavailableFailure = { mountStatus?: SourceMountStatus, accessState?: SourceAccessState, accessIssueKind?: SourceLifecycleIssueKind, };

export type HashSourceFilesBlake3SourceRootMissingFailure = { detail?: string, };

export type HashSourceFilesBlake3SourceRootBlockedFailure = { accessIssueKind?: SourceLifecycleIssueKind, detail?: string, };

export type HashSourceFilesBlake3FileFailure = { "type": "sourceFileNotFound" } | { "type": "sourceFileUnavailable", "payload": HashSourceFilesBlake3SourceFileUnavailableFailure } | { "type": "sourceRootUnavailable", "payload": HashSourceFilesBlake3SourceUnavailableFailure } | { "type": "sourceRootMissing", "payload": HashSourceFilesBlake3SourceRootMissingFailure } | { "type": "sourceRootBlocked", "payload": HashSourceFilesBlake3SourceRootBlockedFailure } | { "type": "invalidRelativePath", "payload": HashSourceFilesBlake3InvalidRelativePathFailure } | { "type": "sourceFilePathEscapesRoot" } | { "type": "physicalFileMissing" } | { "type": "physicalFileBlocked", "payload": HashSourceFilesBlake3IoFailure } | { "type": "fileOpen", "payload": HashSourceFilesBlake3IoFailure } | { "type": "fileRead", "payload": HashSourceFilesBlake3IoFailure } | { "type": "basisChanged" } | { "type": "storeFailure" };

export type HashSourceFilesBlake3SourceFileUnavailableFailure = { presenceState: string, };

export type HashSourceFilesBlake3InvalidRelativePathFailure = { reason: string, };

export type HashSourceFilesBlake3IoFailure = { detail: string, };

export type SourceMaintenanceEffectiveLimits = { hashLimit: number, attachmentLimit: number, probeLimit: number, promotionLimit: number, identityCandidateLimit: number, identityDecisionLimit: number, };

export type SourceMaintenanceHashSummary = { effectiveLimit: number, hashedCount: number, skippedCount: number, failedCount: number, remainingCandidates: number, };

export type SourceMaintenanceAttachmentMaterializationSummary = { effectiveLimit: number, attachmentsCreated: number, attachmentsRefreshed: number, linksCreated: number, linksReplaced: number, linksRefreshed: number, skippedStaleObservations: number, skippedNoBlake3: number, skippedNoObservations: number, remainingCandidates: number, };

export type SourceMaintenanceProbeSummary = { effectiveLimit: number, probedCount: number, skippedCount: number, failedCount: number, remainingCandidates: number, };

export type SourceMaintenancePlayableMediaPromotionSummary = { effectiveLimit: number, promotedCount: number, refreshedCount: number, skippedUnusableSource: number, skippedUnsupportedMediaKind: number, skippedNoObservations: number, skippedStaleObservations: number, skippedNoBlake3: number, skippedNoProbeObservations: number, skippedMissingAttachmentLink: number, skippedStaleAttachmentLink: number, remainingCandidates: number, };

export type SourceMaintenanceTrackIdentityCandidateSummary = { effectiveLimit: number, candidatesCreated: number, candidatesRefreshed: number, membersCreated: number, membersRefreshed: number, evidenceCreated: number, evidenceRefreshed: number, candidatesMarkedStale: number, skippedStalePlayableMedia: number, remainingCandidates: number, };

export type SourceMaintenanceTrackIdentityDecisionSummary = { effectiveLimit: number, decisionsCreated: number, decisionEvidenceCreated: number, skippedStaleCandidates: number, skippedExistingCurrentDecisions: number, skippedUserBlockedCandidates: number, remainingCandidates: number, };

export type SourceMaintenanceAttachmentLinkSummary = { currentLinksCount: number, staleLinksCount: number, sourceFilesWithCurrentBlake3ObservationsCount: number, sourceFilesWithAttachmentLinksCount: number, sourceFilesMissingAttachmentLinksCount: number, unmaterializedBlake3ObservationsCount: number, };

export type SourceMaintenanceLastRunSummary = { status: SourceMaintenanceRunStatus, hash: SourceMaintenanceHashSummary, attachmentMaterialization: SourceMaintenanceAttachmentMaterializationSummary, probe: SourceMaintenanceProbeSummary, playableMediaPromotion: SourceMaintenancePlayableMediaPromotionSummary, trackIdentityCandidates: SourceMaintenanceTrackIdentityCandidateSummary, trackIdentityDecisions: SourceMaintenanceTrackIdentityDecisionSummary, remainingHashCandidates: number, remainingProbeCandidates: number, remainingPlayableMediaPromotionCandidates: number, remainingTrackIdentityCandidateProductionCandidates: number, remainingTrackIdentityDecisionProductionCandidates: number, sourceFailure?: SourceMaintenanceSourceFailure, };

export type SourceMaintenanceRunStatus = "completed" | "partial" | "skipped" | "failed";

export type SourceMaintenanceSnapshotStatus = "idle" | "running" | "unavailable" | "blocked" | "failed";

export type SourceMaintenanceSourceFailure = { "type": "sourceNotFound" } | { "type": "sourceUnavailable", "payload": SourceMaintenanceSourceUnavailableFailure } | { "type": "sourceRootMissing", "payload": SourceMaintenanceSourceRootMissingFailure } | { "type": "sourceRootBlocked", "payload": SourceMaintenanceSourceRootBlockedFailure };

export type SourceMaintenanceSourceUnavailableFailure = { mountStatus?: SourceMountStatus, accessState?: SourceAccessState, accessIssueKind?: SourceLifecycleIssueKind, };

export type SourceMaintenanceSourceRootMissingFailure = { detail?: string, };

export type SourceMaintenanceSourceRootBlockedFailure = { accessIssueKind?: SourceLifecycleIssueKind, detail?: string, };

export type CommandOutcome = { "type": "success", "payload": CommandSuccessEnvelope } | { "type": "error", "payload": CommandErrorEnvelope };

export type CommandSuccessEnvelope = { reply: CommandReply, };

export type CommandErrorEnvelope = { error: ProtocolError, };

export type ProtocolError = { "type": "invalidRequest", "payload": { detail: string, } } | { "type": "durableStoreFailure", "payload": { detail: string, } } | { "type": "hostFailure", "payload": { detail: string, } };

export type LibraryBoundaryEvent = { "type": "sourceScanEvent", "payload": SourceScanEvent } | { "type": "maintainedSnapshotInvalidated", "payload": MaintainedSnapshotEvent };

export type SourceScanEvent = { eventSequence: number, occurredAtMs: number, kind: SourceScanEventKind, rootId: string, scanRunId: string, phase: ScanRunPhase, directoriesVisited: number, filesVisited: number, filesDiscovered: number, mediaCandidates: number, queuedWorkItems: number, detail: string | null, };

export type SourceScanEventKind = "sourceScanStarted" | "sourceScanProgressed" | "sourceScanCompleted" | "sourceScanFailed" | "sourceScanBlocked" | "sourceScanCancelled";

export type ScanRunPhase = "scanning" | "blocked" | "interrupted";

export type MaintainedSnapshotEvent = { eventSequence: number, occurredAtMs: number, invalidation: MaintainedSnapshotInvalidation, };

export type MaintainedSnapshotInvalidation = { scope: MaintainedSnapshotScope, revision: MaintainedSnapshotRevision | null, };

export type MaintainedSnapshotScopeRevision = { scope: MaintainedSnapshotScope, revision: MaintainedSnapshotRevision, };

export type MaintainedSnapshotScope = "navigationRows" | "contents";

export type MaintainedSnapshotRevision = string;

export type LibraryBoundaryContract = { commandRequest: CommandRequest, commandOutcome: CommandOutcome, protocolError: ProtocolError, libraryBoundaryEvent: LibraryBoundaryEvent, };

