use schemars::{JsonSchema, schema_for};
use ts_rs::{Config, TS};

use crate::{CommandOutcome, CommandRequest, LibraryBoundaryEvent, ProtocolError};

const GENERATED_HEADER: &str = "\
// @generated by cargo run -p xtask -- export-boundary-contract
// Source of truth: crates/library-boundary-protocol
// Do not edit by hand.

";

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LibraryBoundaryContract {
    pub command_request: CommandRequest,
    pub command_outcome: CommandOutcome,
    pub protocol_error: ProtocolError,
    pub library_boundary_event: LibraryBoundaryEvent,
}

pub fn generated_contract_index_ts() -> String {
    let cfg = Config::new().with_large_int("number");
    let mut output = String::from(GENERATED_HEADER);

    push_ts_decl::<CommandRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryBoundaryEventStreamCommand>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryBoundaryEventsAfterRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryRootCommand>(&cfg, &mut output);
    push_ts_decl::<crate::RegisterLocalRootRequest>(&cfg, &mut output);
    push_ts_decl::<crate::SourceRegistrationRootClass>(&cfg, &mut output);
    push_ts_decl::<crate::RegisteredLocalRoot>(&cfg, &mut output);
    push_ts_decl::<crate::SourceRegistrationProposalRequired>(&cfg, &mut output);
    push_ts_decl::<crate::SourceRegistrationRejected>(&cfg, &mut output);
    push_ts_decl::<crate::StartRootScanRequest>(&cfg, &mut output);
    push_ts_decl::<crate::CancelRootScanRequest>(&cfg, &mut output);
    push_ts_decl::<crate::CancelRootScanStatus>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLocalRootsRequest>(&cfg, &mut output);
    push_ts_decl::<crate::UnregisterLocalRootRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LocalRootAvailability>(&cfg, &mut output);
    push_ts_decl::<crate::LocalRoot>(&cfg, &mut output);
    push_ts_decl::<crate::SourceFileHashCommand>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3Request>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceCommand>(&cfg, &mut output);
    push_ts_decl::<crate::RunSourceMaintenanceRequest>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityDecisionCommand>(&cfg, &mut output);
    push_ts_decl::<crate::AcceptTrackIdentityCandidateRequest>(&cfg, &mut output);
    push_ts_decl::<crate::RejectTrackIdentityCandidateRequest>(&cfg, &mut output);
    push_ts_decl::<crate::DeferTrackIdentityCandidateRequest>(&cfg, &mut output);
    push_ts_decl::<crate::SnapshotReadCommand>(&cfg, &mut output);
    push_ts_decl::<crate::ReadNavigationRowsRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowByStableKeyRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLocalBrowseEntryPointsRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseEntryPointKind>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseEntryPointStatus>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowsePlatform>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseOperation>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseSourceAdmissionRequestKind>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseProfile>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseEntryPointFailureCode>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLocalBrowseItemsRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItemKind>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItemStatus>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItemMediaRelevance>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItemFailureCode>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryTreeChildrenRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeRowPolicy>(&cfg, &mut output);
    push_ts_decl::<crate::NavigableChildScopeState>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceLifecycleRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceIntegrityRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceMaintenanceRequest>(&cfg, &mut output);
    push_ts_decl::<crate::SourceClass>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMountStatus>(&cfg, &mut output);
    push_ts_decl::<crate::SourceAccessState>(&cfg, &mut output);
    push_ts_decl::<crate::SourceLifecycleIssueKind>(&cfg, &mut output);
    push_ts_decl::<crate::SourceScanPhase>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceFileAttachmentRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadAttachmentSourceFilesRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceAttachmentSummaryRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadTrackIdentityReviewCandidatesRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsReadRequest>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterReadRequest>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterScope>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterRecursion>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterSort>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterResultKind>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterSet>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterFileClass>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterSourceAccessState>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterEvidenceAvailability>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterAttachmentLinkState>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterMediaRelevance>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterIndexState>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterAuthorityLayer>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterEvidenceCoverageState>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterMatchReason>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsScope>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsReadPolicy>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsFileClass>(&cfg, &mut output);
    push_ts_decl::<crate::PlayableMediaKind>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsScopeDepth>(&cfg, &mut output);
    push_ts_decl::<crate::CommandReply>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryBoundaryEventStreamReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryBoundaryEventsAfterReply>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryRootReply>(&cfg, &mut output);
    push_ts_decl::<crate::RegisterLocalRootReply>(&cfg, &mut output);
    push_ts_decl::<crate::StartRootScanReply>(&cfg, &mut output);
    push_ts_decl::<crate::CancelRootScanReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLocalRootsReply>(&cfg, &mut output);
    push_ts_decl::<crate::UnregisterLocalRootReply>(&cfg, &mut output);
    push_ts_decl::<crate::SourceFileHashReply>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3Reply>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceReply>(&cfg, &mut output);
    push_ts_decl::<crate::RunSourceMaintenanceReply>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityDecisionReply>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityDecisionCommandResult>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityDecisionCommandSuccess>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityDecisionCommandFailure>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityDecisionState>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityEffectiveDecisionSummary>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityEffectiveDecisionCurrentStatus>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityEffectiveDecisionPrecedence>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityUserBlockingDecisionState>(&cfg, &mut output);
    push_ts_decl::<crate::SnapshotReadReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadNavigationRowsReply>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowReply>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowByStableKeyReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLocalBrowseEntryPointsReply>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseEntryPointsReadStatus>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseEntryPoint>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseEntryPointIdentity>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseEntryPointFailure>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLocalBrowseItemsReply>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItemsReadStatus>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseWindowIdentity>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItem>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItemIdentity>(&cfg, &mut output);
    push_ts_decl::<crate::LocalBrowseItemFailure>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryTreeChildrenReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceLifecycleReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceIntegrityReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceMaintenanceReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceFileAttachmentReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadAttachmentSourceFilesReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadSourceAttachmentSummaryReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadTrackIdentityReviewCandidatesReply>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewReadStatus>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewCandidate>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewCandidateStatus>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewDecision>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewEvidenceSummary>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewSourceSummary>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewSourceSample>(&cfg, &mut output);
    push_ts_decl::<crate::TrackIdentityReviewState>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsReadReply>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterReadReply>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRow>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRowFamily>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRowKind>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRowSelectorKind>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeEntryPoint>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeWindow>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeCoverage>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeCoverageState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeNode>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeNodeKind>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreeFileClass>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryTreePresenceState>(&cfg, &mut output);
    push_ts_decl::<crate::DirectoryPlayableMediaState>(&cfg, &mut output);
    push_ts_decl::<crate::DirectoryImageMediaState>(&cfg, &mut output);
    push_ts_decl::<crate::DirectoryScanState>(&cfg, &mut output);
    push_ts_decl::<crate::SourceLifecycle>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityAvailability>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityAvailabilityState>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityCoverage>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityInventory>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityFileClass>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityPresenceCount>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityFileClassCount>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityFileKindCount>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityEvidenceAndMaintenance>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityAttachmentIntegrity>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityRuntimeMaintenance>(&cfg, &mut output);
    push_ts_decl::<crate::SourceIntegrityRuntimeMaintenanceState>(&cfg, &mut output);
    push_ts_decl::<crate::AttachmentIdentityReadStatus>(&cfg, &mut output);
    push_ts_decl::<crate::AttachmentIdentity>(&cfg, &mut output);
    push_ts_decl::<crate::AttachmentSourceFileOccurrenceStatus>(&cfg, &mut output);
    push_ts_decl::<crate::SourceFileAttachmentLink>(&cfg, &mut output);
    push_ts_decl::<crate::SourceFileAttachmentLinkStatus>(&cfg, &mut output);
    push_ts_decl::<crate::AttachmentSourceFilesSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceAttachmentSummary>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsResult>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterResult>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterState>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterQueryIdentity>(&cfg, &mut output);
    push_ts_decl::<crate::SearchFilterResultRow>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsState>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsScopeCoverage>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsScopeCoverageState>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsFileRow>(&cfg, &mut output);
    push_ts_decl::<crate::PlayableMedia>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsFileKind>(&cfg, &mut output);
    push_ts_decl::<crate::ContentsPresenceState>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3Outcome>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3OutcomeStatus>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3HashedOutcome>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3SkippedOutcome>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3FailedOutcome>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3SkipReason>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3SourceFailure>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3SourceUnavailableFailure>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3SourceRootMissingFailure>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3SourceRootBlockedFailure>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3FileFailure>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3SourceFileUnavailableFailure>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3InvalidRelativePathFailure>(&cfg, &mut output);
    push_ts_decl::<crate::HashSourceFilesBlake3IoFailure>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceEffectiveLimits>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceHashSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceAttachmentMaterializationSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceProbeSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenancePlayableMediaPromotionSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceTrackIdentityCandidateSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceTrackIdentityDecisionSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceAttachmentLinkSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceLastRunSummary>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceRunStatus>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceSnapshotStatus>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceSourceFailure>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceSourceUnavailableFailure>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceSourceRootMissingFailure>(&cfg, &mut output);
    push_ts_decl::<crate::SourceMaintenanceSourceRootBlockedFailure>(&cfg, &mut output);
    push_ts_decl::<CommandOutcome>(&cfg, &mut output);
    push_ts_decl::<crate::CommandSuccessEnvelope>(&cfg, &mut output);
    push_ts_decl::<crate::CommandErrorEnvelope>(&cfg, &mut output);
    push_ts_decl::<ProtocolError>(&cfg, &mut output);
    push_ts_decl::<LibraryBoundaryEvent>(&cfg, &mut output);
    push_ts_decl::<crate::SourceScanEvent>(&cfg, &mut output);
    push_ts_decl::<crate::SourceScanEventKind>(&cfg, &mut output);
    push_ts_decl::<crate::ScanRunPhase>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotEvent>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotInvalidation>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotScopeRevision>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotScope>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotRevision>(&cfg, &mut output);
    push_ts_decl::<LibraryBoundaryContract>(&cfg, &mut output);

    output
}

pub fn generated_contract_schema_json() -> Result<String, serde_json::Error> {
    let schema = schema_for!(LibraryBoundaryContract);
    let mut output = String::new();
    output.push_str(&serde_json::to_string_pretty(&schema)?);
    output.push('\n');
    Ok(output)
}

pub const fn protocol_crate_name() -> &'static str {
    env!("CARGO_PKG_NAME")
}

pub const fn protocol_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

fn push_ts_decl<T>(cfg: &Config, output: &mut String)
where
    T: TS,
{
    output.push_str("export ");
    output.push_str(&T::decl(cfg));
    output.push_str("\n\n");
}

#[cfg(test)]
mod tests {
    use super::{generated_contract_index_ts, generated_contract_schema_json};

    #[test]
    fn generated_typescript_exports_outer_contract_and_protocol_error() {
        let ts = generated_contract_index_ts();

        assert!(ts.contains("export type CommandRequest"));
        assert!(ts.contains("export type CommandOutcome"));
        assert!(ts.contains("export type ProtocolError"));
        assert!(ts.contains("registerLocalRoot"));
        assert!(ts.contains("startRootScan"));
        assert!(ts.contains("readLocalRoots"));
        assert!(ts.contains("unregisterLocalRoot"));
        assert!(ts.contains("readSourceLifecycle"));
        assert!(ts.contains("SourceLifecycle"));
        assert!(ts.contains("readLibraryTreeChildren"));
        assert!(ts.contains("export type LibraryTreeRowPolicy"));
        assert!(ts.contains("rowPolicy?: LibraryTreeRowPolicy"));
        assert!(ts.contains("LibraryTreeNode"));
        assert!(ts.contains("LibraryTreeFileClass"));
        assert!(ts.contains("fileClass: ContentsFileClass"));
        assert!(ts.contains("playableMediaBrowse"));
        assert!(ts.contains("hasPolicyOmittedRows: boolean"));
        assert!(!ts.contains(&["media", "Class"].concat()));
        assert!(!ts.contains(&["Contents", "Media", "Class"].concat()));
        assert!(ts.contains("DirectoryPlayableMediaState"));
        assert!(ts.contains("DirectoryImageMediaState"));
        assert!(ts.contains("DirectoryScanState"));
        assert!(ts.contains("acceptTrackIdentityCandidate"));
        assert!(ts.contains("TrackIdentityDecisionCommand"));
        assert!(ts.contains("navigationRowId: string"));
        assert!(ts.contains("rowVersion: string"));
    }

    #[test]
    fn generated_typescript_exports_typed_search_filter_status_fields() {
        let ts = generated_contract_index_ts();

        assert!(ts.contains("export type SearchFilterIndexState"));
        assert!(ts.contains("export type SearchFilterAuthorityLayer"));
        assert!(ts.contains("export type SearchFilterEvidenceCoverageState"));
        assert!(ts.contains("export type SearchFilterMatchReason"));
        assert!(ts.contains("indexState: SearchFilterIndexState"));
        assert!(ts.contains("authorityLayer: SearchFilterAuthorityLayer"));
        assert!(ts.contains("attachmentLinkState: SearchFilterAttachmentLinkState"));
        assert!(ts.contains("evidenceCoverageState: SearchFilterEvidenceCoverageState"));
        assert!(ts.contains("matchReason: SearchFilterMatchReason"));
        assert!(ts.contains("\"notApplicable\""));
        assert!(ts.contains("\"partial\""));
    }

    #[test]
    fn generated_schema_exports_outer_contract_and_protocol_error() {
        let schema = generated_contract_schema_json().expect("generate schema");

        assert!(schema.contains("\"CommandRequest\""));
        assert!(schema.contains("\"CommandOutcome\""));
        assert!(schema.contains("\"ProtocolError\""));
        assert!(schema.contains("\"registerLocalRoot\""));
        assert!(schema.contains("\"readSourceLifecycle\""));
        assert!(schema.contains("\"readLibraryTreeChildren\""));
        assert!(schema.contains("\"fileClass\""));
        assert!(schema.contains("\"playableMediaBrowse\""));
        assert!(schema.contains("\"hasPolicyOmittedRows\""));
        assert!(!schema.contains(&format!("\"{}\"", ["media", "Class"].concat())));
        assert!(!schema.contains(&format!("\"{}\"", ["Contents", "Media", "Class"].concat())));
        assert!(schema.contains("\"acceptTrackIdentityCandidate\""));
        assert!(schema.contains("\"protocolError\""));
        assert!(schema.contains("\"navigationRowId\""));
        assert!(schema.contains("\"type\": \"string\""));
    }
}
