use schemars::{JsonSchema, schema_for};
use ts_rs::{Config, TS};

use crate::{CommandOutcome, CommandRequest, LibraryBoundaryEvent, ProtocolError};

const GENERATED_HEADER: &str = "\
// @generated by cargo run -p xtask -- export-boundary-contract
// Source of truth: crates/library-boundary-protocol
// Do not edit by hand.

";

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, JsonSchema, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct LibraryBoundaryContract {
    pub command_request: CommandRequest,
    pub command_outcome: CommandOutcome,
    pub protocol_error: ProtocolError,
    pub library_boundary_event: LibraryBoundaryEvent,
}

pub fn generated_contract_index_ts() -> String {
    let cfg = Config::new().with_large_int("number");
    let mut output = String::from(GENERATED_HEADER);

    push_ts_decl::<CommandRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryBoundaryEventStreamCommand>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryBoundaryEventsRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryRootCommand>(&cfg, &mut output);
    push_ts_decl::<crate::RegisterLocalRootRequest>(&cfg, &mut output);
    push_ts_decl::<crate::RunRootScanRequest>(&cfg, &mut output);
    push_ts_decl::<crate::PlaylistWriteCommand>(&cfg, &mut output);
    push_ts_decl::<crate::CreatePlaylistRequest>(&cfg, &mut output);
    push_ts_decl::<crate::RenamePlaylistRequest>(&cfg, &mut output);
    push_ts_decl::<crate::DeletePlaylistRequest>(&cfg, &mut output);
    push_ts_decl::<crate::AppendLibraryAssetToPlaylistRequest>(&cfg, &mut output);
    push_ts_decl::<crate::RemoveLibraryAssetFromPlaylistRequest>(&cfg, &mut output);
    push_ts_decl::<crate::MovePlaylistEntryRequest>(&cfg, &mut output);
    push_ts_decl::<crate::SnapshotReadCommand>(&cfg, &mut output);
    push_ts_decl::<crate::ReadNavigationRowsRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowRequest>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowByStableKeyRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLiteralHierarchyChildrenRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadNavigationNodeLibraryBrowserWindowRequest>(&cfg, &mut output);
    push_ts_decl::<crate::SearchNavigationNodeLibraryBrowserWindowRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryAssetWaveformOverviewRequest>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryAssetPreparationDetailRequest>(&cfg, &mut output);
    push_ts_decl::<crate::CommandReply>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryBoundaryEventStreamReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryBoundaryEventsReply>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryRootReply>(&cfg, &mut output);
    push_ts_decl::<crate::RegisterLocalRootReply>(&cfg, &mut output);
    push_ts_decl::<crate::RunRootScanReply>(&cfg, &mut output);
    push_ts_decl::<crate::PlaylistWriteReply>(&cfg, &mut output);
    push_ts_decl::<crate::CreatePlaylistReply>(&cfg, &mut output);
    push_ts_decl::<crate::RenamePlaylistReply>(&cfg, &mut output);
    push_ts_decl::<crate::DeletePlaylistReply>(&cfg, &mut output);
    push_ts_decl::<crate::AppendLibraryAssetToPlaylistReply>(&cfg, &mut output);
    push_ts_decl::<crate::RemoveLibraryAssetFromPlaylistReply>(&cfg, &mut output);
    push_ts_decl::<crate::MovePlaylistEntryReply>(&cfg, &mut output);
    push_ts_decl::<crate::SnapshotReadReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadNavigationRowsReply>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowReply>(&cfg, &mut output);
    push_ts_decl::<crate::LoadNavigationRowByStableKeyReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLiteralHierarchyChildrenReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadNavigationNodeLibraryBrowserWindowReply>(&cfg, &mut output);
    push_ts_decl::<crate::SearchNavigationNodeLibraryBrowserWindowReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryAssetWaveformOverviewReply>(&cfg, &mut output);
    push_ts_decl::<crate::ReadLibraryAssetPreparationDetailReply>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRow>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRowFamily>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRowKind>(&cfg, &mut output);
    push_ts_decl::<crate::NavigationRowSelectorKind>(&cfg, &mut output);
    push_ts_decl::<crate::LiteralHierarchyEntryPoint>(&cfg, &mut output);
    push_ts_decl::<crate::LiteralHierarchyWindow>(&cfg, &mut output);
    push_ts_decl::<crate::LiteralHierarchyNode>(&cfg, &mut output);
    push_ts_decl::<crate::LiteralHierarchyNodeKind>(&cfg, &mut output);
    push_ts_decl::<crate::LiteralHierarchyPresenceState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryBrowserWindow>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetBrowserRow>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetAvailabilityState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetStemsStateSummary>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPrepReadinessSummary>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationDetail>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationDetailGroup>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationDetailGroupKey>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationDetailRow>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationCapabilityKey>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationRequirementClass>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationOutcomeKind>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationWorkState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationOutcomeState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationSatisfactionState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationArtifactCoverageState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetPreparationProgress>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetWaveformOverview>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetWaveformOverviewBucket>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetWaveformOverviewCapabilityState>(&cfg, &mut output);
    push_ts_decl::<crate::LibraryAssetWaveformOverviewAmplitudeScale>(&cfg, &mut output);
    push_ts_decl::<CommandOutcome>(&cfg, &mut output);
    push_ts_decl::<crate::CommandSuccessEnvelope>(&cfg, &mut output);
    push_ts_decl::<crate::CommandErrorEnvelope>(&cfg, &mut output);
    push_ts_decl::<ProtocolError>(&cfg, &mut output);
    push_ts_decl::<LibraryBoundaryEvent>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotInvalidation>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotScopeRevision>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotScope>(&cfg, &mut output);
    push_ts_decl::<crate::MaintainedSnapshotRevision>(&cfg, &mut output);
    push_ts_decl::<LibraryBoundaryContract>(&cfg, &mut output);

    output
}

pub fn generated_contract_schema_json() -> Result<String, serde_json::Error> {
    let schema = schema_for!(LibraryBoundaryContract);
    let mut output = String::new();
    output.push_str(&serde_json::to_string_pretty(&schema)?);
    output.push('\n');
    Ok(output)
}

pub const fn protocol_crate_name() -> &'static str {
    env!("CARGO_PKG_NAME")
}

pub const fn protocol_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

fn push_ts_decl<T>(cfg: &Config, output: &mut String)
where
    T: TS,
{
    output.push_str("export ");
    output.push_str(&T::decl(cfg));
    output.push_str("\n\n");
}

#[cfg(test)]
mod tests {
    use super::{generated_contract_index_ts, generated_contract_schema_json};

    #[test]
    fn generated_typescript_exports_outer_contract_and_protocol_error() {
        let ts = generated_contract_index_ts();

        assert!(ts.contains("export type CommandRequest"));
        assert!(ts.contains("export type CommandOutcome"));
        assert!(ts.contains("export type ProtocolError"));
        assert!(ts.contains("registerLocalRoot"));
        assert!(ts.contains("runRootScan"));
        assert!(ts.contains("readLiteralHierarchyChildren"));
        assert!(ts.contains("LiteralHierarchyNode"));
        assert!(ts.contains("readNavigationNodeLibraryBrowserWindow"));
        assert!(ts.contains("searchNavigationNodeLibraryBrowserWindow"));
        assert!(ts.contains("readLibraryAssetPreparationDetail"));
        assert!(ts.contains("LibraryAssetPreparationDetailGroupKey"));
        assert!(!ts.contains("readLibraryBrowserWindow"));
        assert!(!ts.contains("searchLibraryBrowserWindow"));
        assert!(ts.contains("navigationRowId: string"));
        assert!(ts.contains("rowVersion: string"));
    }

    #[test]
    fn generated_schema_exports_outer_contract_and_protocol_error() {
        let schema = generated_contract_schema_json().expect("generate schema");

        assert!(schema.contains("\"CommandRequest\""));
        assert!(schema.contains("\"CommandOutcome\""));
        assert!(schema.contains("\"ProtocolError\""));
        assert!(schema.contains("\"registerLocalRoot\""));
        assert!(schema.contains("\"readLiteralHierarchyChildren\""));
        assert!(schema.contains("\"protocolError\""));
        assert!(schema.contains("\"navigationRowId\""));
        assert!(schema.contains("\"type\": \"string\""));
    }
}
